/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.6.0
*/
FusionCharts.register("module",["private","modules.renderer.js-gradientlegend",function(){function V(b,e,m){var l=b[0],n=b[1];b=b[2];l+=(e[0]-l)*m;n+=(e[1]-n)*m;e=b+(e[2]-b)*m;return{hex:(ta+(l<<16|n<<8|e).toString(16)).slice(-6),rgb:[l,n,e]}}function fa(b,e){return b.maxvalue-e.maxvalue}function D(b){var e,m,l=b.colorRange||{},n=b.dataMin,C=b.dataMax,q=b.sortLegend||!1,g=b.mapByCategory||!1,v=b.defaultColor,d=b.numberFormatter,c=l.color;b=this.colorArr=[];var h,f,a;this.mapByCategory=g;"1"===l.mapbypercent&&
(this.mapbypercent=!0);if("1"===l.gradient&&!g){this.gradient=!0;m=Ca(ba(l.startcolor,l.mincolor,l.code));q=ia(Ca(ba(m,v,"CCCCCC")));g=this.scaleMin=G(l.startvalue,l.minvalue,this.mapbypercent?0:n);b.push({code:m,maxvalue:g,label:Y(l.startlabel),codeRGB:ia(m)});if(c&&(e=c.length))for(n=0;n<e;n+=1)v=c[n],m=Ca(ba(v.color,v.code)),f=G(v.value,v.maxvalue),a=G(v.minvalue),f>g&&b.push({code:m,maxvalue:f,userminvalue:a,label:Y(ba(v.label,v.displayvalue)),codeRGB:ia(m)});b.sort(fa);e=b.length;for(n=1;n<e;n+=
1)v=b[n],m=v.maxvalue-g,0<m?(v.minvalue=g,v.range=m,g=v.maxvalue):(b.splice(n,1),--n,--e);2<=b.length&&(this.scaleMax=g,b[n-1].label=ba(l.endlabel,b[n-1].label,b[n-1].displayvalue));1===b.length&&(f=G(l.maxvalue,this.mapbypercent?100:C),b.push({minvalue:g,maxvalue:f,range:f-g,label:l.endlabel}),this.scaleMax=f,delete b[0].code);l=b[0];C=b[b.length-1];l.code&&C.code||(m=ja(q),e=Fa((m[2]=0,m)),m=Fa((m[2]=100,m)),l.code||(l.codeRGB=e,l.code=ua(e)),C.code||(C.codeRGB=m,C.code=ua(m)));e=b.length;for(n=
1;n<e;n+=1)if(v=b[n],v.code){if(h)for(C=v,a=l.maxvalue,c=C.maxvalue-a;h<n;h+=1)q=b[h],m=V(l.codeRGB,C.codeRGB,(q.maxvalue-a)/c),q.code=m.hex,q.codeRGB=m.rgb;h=null;l=v}else h=h||n;if(void 0===this.scaleMin||void 0===this.scaleMax)this.noValidRange=!0}else if(c&&(e=c.length)){for(n=0;n<e;n+=1)v=c[n],m=ba(v.color,v.code),f=G(v.maxvalue),a=G(v.minvalue),h=ba(v.label,v.displayvalue,g?Z:d.dataLabels(a)+" - "+d.dataLabels(f)),(m&&f>a||g&&h)&&b.push({code:m,maxvalue:f,minvalue:a,label:Y(h),labelId:h.toLowerCase()});
b.length?q&&b.sort(fa):this.noValidRange=!0}}function O(b,e){return e?A(100*b)/100+"%":ca(b,Z).toString()}var la=this,b=la.hcLib,va=la.window,va=/msie/i.test(va.navigator.userAgent)&&!va.opera,G=b.pluckNumber,ta=b.COLOR_BLACK,e=b.COLOR_GLASS,Da=b.FC_CONFIG_STRING,xa=b.graphics,Fa=xa.HSBtoRGB,ja=xa.RGBtoHSB,ua=xa.RGBtoHex,ia=xa.HEXtoRGB,ma=b.COMMASTRING,Z=b.BLANKSTRING,Y=b.parseUnsafeString,wa=b.graphics.convertColor,Ga=b.POSITION_TOP,ka=b.POSITION_MIDDLE,ya=b.POSITION_START,Ha=b.POSITION_END,za=b.graphics.getDarkColor,
ra=b.graphics.getLightColor,ba=b.pluck,ca=b.getValidValue,sa=b.toRaphaelColor,Aa=b.hasTouch,A=Math.round,T=Math.max,Q=Math.min,Ia=Math.abs,W,Ja,Ba,Ka="rgba(192,192,192,"+(va?.002:1E-6)+")",Ca=function(b){return b&&b.replace(/^#?([a-f0-9]+)/ig,"$1")};D.prototype={getColorObj:function(b){var e=this.colorArr,m=this.gradient?1:0,l=e[m],n;if(this.mapByCategory){for(b=Y(b).toLowerCase();l;){if(l.labelId===b)return{code:l.code,seriesIndex:m};m+=1;l=e[m]}return{outOfRange:!0}}if(this.gradient){if(this.scaleMin<=
b&&this.scaleMax>=b){for(;l&&l.maxvalue<b;)m+=1,l=e[m];b=(b-l.minvalue)/l.range;return{code:V(e[m-1].codeRGB,l.codeRGB,b).hex}}return{outOfRange:!0}}for(;l;){if(l.maxvalue>b&&l.minvalue<=b)return{code:l.code,seriesIndex:m};l.maxvalue===b&&(n=m);m+=1;l=e[m]}return(l=e[n])&&l.maxvalue===b?{code:l.code,seriesIndex:n}:{outOfRange:!0}}};D.prototype.constructor=D;b.colorRange=D;W=b.configureGradientLegendOptions=function(b,e){var m=b.legend,l=e.chart;m.legendSliderBorderWidth=G(l.legendpointerborderthickness,
1);m.legendSliderBorderColor=wa(ba(l.legendpointerbordercolor,ta),G(l.legendpointerborderalpha,100));m.legendSliderWidth=G(l.legendpointerwidth,l.legendpointerswidth,12);m.legendSliderHeight=G(l.legendpointerheight,l.legendpointersheight,12);m.legendColorBoxBorderColor=m.borderColor;m.legendColorBoxBorderWidth=m.borderWidth;m.legendScaleColor=wa(ba(l.legendscalelinecolor,ta),G(l.legendscalelinealpha,100));m.legendScalePadding=G(l.legendscalepadding,4);m.legendScaleLineThickness=G(l.legendscalelinethickness,
1);m.legendScaleTickDistance=G(l.legendscaletickdistance,6);m.itemStyle.cursor="default";m.interActivity=G(l.interactivelegend,1)};b.placeGLegendBlockRight=function(b,e,m,l,n){this.configureLegendOptions(b,e.chart,!0,n,m);W(b,e);n=this.snapLiterals||(this.snapLiterals={});var C=b[Da],q=this.smartLabel||C.smartLabel,g=b.legend,v=b.chart.spacingRight,d,c,h=g.textPadding=2,f=2*h,a=g.title.padding,E=0,ga=0,k=2*g.padding;e=G(e.chart.legendpadding,7)+g.borderWidth/2+1;var w=b.colorRange||{},I=w.colorArr,
P=w.mapbypercent,U=w.scaleMin,t=w.scaleMax-U,da=g.legendSliderWidth,y=g.legendSliderHeight/2;c=g.legendScalePadding;var r=g.legendScaleTickDistance,x=g.itemStyle||{};d=G(parseInt(x.lineHeight,10)||12);var z=.75*d,R=m-k,B,N,p=0,H,u,J,L,F,K,oa;l-=k;if(!w.noValidRange&&I&&1<(N=I.length)){--N;g.title.text!==Z&&(q.setStyle(g.title.style),d=q.getSmartText(g.title.text,R,T(d,l/4)),g.title.text=d.text,E=d.width+k,l-=ga=d.height+a);q.setStyle(x);d=q.lineHeight;R-=r+c+da;g.colorBoxX=da;a=T(d,R/2);R=Q(R-a-4,
d);H=T(d,l/2);B=l/4;r=I[0];r.scaleLabel=O(r.maxvalue,P);d=q.getSmartText(r.label,B,R);r.label=d.text;x=d.height;r.labelY=z-d.height/2;c=q.getSmartText(r.scaleLabel,a,H);r.scaleLabel=c.text;w=c.height/2;u=c.width;r.scaleLabelY=z-c.height/2;g.colorBoxY=T(w,d.width+f,y)+ga;r=oa=I[N];r.scaleLabel=O(r.maxvalue,P);d=q.getSmartText(r.label,B,R);r.label=d.text;x=T(x,d.height);r.labelY=z-d.height/2;c=q.getSmartText(r.scaleLabel,a,H);r.scaleLabel=c.text;u=T(u,c.width);B=c.height/2;d=T(d.width+f,B,y);r.scaleLabelY=
z-c.height/2;g.colorBoxHeight=y=l-g.colorBoxY-d;H=y-B;J=y/t;F=Q(y-p,H-w)-4;for(B=1;B<N;B+=1)r=I[B],L=(r.maxvalue-U)*J,d=q.getSmartText(r.label,2*Q(L-p,y-L),R),r.label=d.text,x=T(x,d.height),r.labelY=z-d.height/2,d=d.width/2,r.scaleLabel=O(r.maxvalue,P),c=q.getSmartText(r.scaleLabel,a,2*Q(L-w,H-L)),r.scaleLabel=c.text,u=T(u,c.width),K=c.height/2,r.scaleLabelY=z-c.height/2,F=Q(F,(L-T(K+w,d+p)-4)*t/r.range),p=d+L,w=K+L;F=T(Q(F,(Q(H-w,y-p)-4)*t/oa.range,.3*l),0);g.colorBoxHeight-=F;g.colorBoxWidth=x&&
x+f||15;g.height=g.totalHeight=l+ga+k-F;g.width=(u&&u+h)+g.colorBoxWidth+da+g.legendScaleTickDistance+g.legendScalePadding+k;g.width<E&&(g.colorBoxX+=(E-g.width)/2,g.width=E);g.width>m&&(g.width=m);n.legendstartx=C.width-v-g.width;n.legendwidth=g.width;n.legendendx=n.legendstartx+n.legendwidth;n.legendheight=g.height;e+=g.width;b.chart.marginRight+=e;return e}g.enabled=!1;return 0};b.placeGLegendBlockBottom=function(b,e,m,l,n){this.configureLegendOptions(b,e.chart,!1,n,m);W(b,e);n=this.snapLiterals||
(this.snapLiterals={});var C=b[Da],q=this.smartLabel||C.smartLabel,g=b.legend,v=b.chart,d=v.spacingBottom,c=v.spacingLeft,v=v.spacingRight,h,f,a=g.textPadding=2,E=g.title.padding,ga=0,k=0,w=2*g.padding;e=G(e.chart.legendpadding,7)+g.borderWidth/2+1;var I=b.colorRange||{},P=I.colorArr,U=I.mapbypercent,t=I.scaleMin,da=I.scaleMax-t,y=g.legendSliderWidth,r=g.legendSliderHeight,x=g.legendScalePadding,z=g.legendScaleTickDistance,R=g.itemStyle||{};h=G(parseInt(R.lineHeight,10)||12);var B=.75*h,N=l-w,p,H,
u,J,L=0,F,K,oa;m-=w;if(!I.noValidRange&&P&&1<(H=P.length)){--H;g.title.text!==Z&&(q.setStyle(g.title.style),h=q.getSmartText(g.title.text,m,N/3),g.title.text=h.text,ga=h.width+w,N-=k=h.height+E);q.setStyle(R);h=q.lineHeight;N-=z+x+r;E=T(h,N/2);R=Q(N-E-4,h);p=m/4;J=2*p;u=P[0];u.scaleLabel=O(u.maxvalue,U);h=q.getSmartText(u.label,p,R);u.label=h.text;N=h.height;u.labelY=B-h.height/2;f=q.getSmartText(u.scaleLabel,J,E);u.scaleLabel=f.text;x=f.width/2;z=f.height;u.code||(u.code=ba(g.minColor,"CCCCCC"));
g.colorBoxX=T(x,h.width+a,y);u=I=P[H];u.scaleLabel=O(u.maxvalue,U);h=q.getSmartText(u.label,p,R);u.label=h.text;N=T(N,h.height);u.labelY=B-h.height/2;f=q.getSmartText(u.scaleLabel,J,E);u.scaleLabel=f.text;z=T(z,f.height);u=f.width/2;h=T(h.width+a,u,y);g.colorBoxWidth=y=m-g.colorBoxX-h;J=y-u;F=y/da;oa=Q(y-L,J-x)-4;for(p=1;p<H;p+=1)u=P[p],K=(u.maxvalue-t)*F,h=q.getSmartText(u.label,2*Q(K-L,y-K),R),u.label=h.text,N=T(N,h.height),u.labelY=B-h.height/2,h=h.width/2,u.scaleLabel=O(u.maxvalue,U),f=q.getSmartText(u.scaleLabel,
2*Q(K-x,J-K),E),u.scaleLabel=f.text,z=T(z,f.height),f=f.width/2,oa=Q(oa,(K-T(f+x,h+L)-4)*da/u.range),L=h+K,x=f+K;oa=T(Q(oa,(Q(J-x,y-L)-4)*da/I.range,.3*m),0);g.colorBoxWidth-=oa;g.width=m+w-oa;g.width<ga&&(g.colorBoxX+=(ga-g.width)/2,g.width=ga);g.colorBoxY=k+r;g.colorBoxHeight=N&&N+2*a||15;g.height=g.totalHeight=(z&&z+a)+g.colorBoxHeight+k+r+g.legendScaleTickDistance+g.legendScalePadding+w;g.height>l&&(g.height=l);n.legendstartx=c+.5*(C.width-c-v-g.width)+(g.x||0);n.legendwidth=g.width;n.legendendx=
n.legendstartx+n.legendwidth;n.legendstarty=C.height-d-g.height;n.legendheight=g.height;n.legendendy=n.legendstarty+n.legendheight;e+=g.height;b.chart.marginBottom+=e;return e}g.enabled=!1;return 0};Ja=function(){return{point:this}};Ba=function(b){return A(100*b)/100};b.rendererRoot.drawGradientLegendItem=function(b){var D=this,m=D.paper,l=D.options,n=D.canvasLeft,C=D.canvasTop,q=D.canvasWidth,g=D.canvasHeight,v=l.colorRange,d,c,h,f,a=l.legend,E=G(a.padding,4),ga=a.itemStyle,l=a.symbolStyle,k=a.interActivity,
w=b.elements;b=w.elementGroup.trackTooltip(!0);var I="vertical"===a.layout,P,U,t,da,y,r,x=0,z=a.lighting3d,R=a.colorBoxWidth,B=a.colorBoxHeight,N=R,p=B,H={FCcolor:{color:Z,alpha:Z,angle:0,ratio:Z}},u=H.FCcolor,J=a.colorBoxX+E,L=a.colorBoxY+E,F,K,oa=a.legendColorBoxBorderColor,Oa=a.legendColorBoxBorderWidth,Ea=["M"],La=a.legendScaleColor;r=a.legendScalePadding;var ea=a.legendScaleLineThickness,W=ea%2/2;c=a.legendScaleTickDistance;var V=a.legendSliderWidth,Q=a.legendSliderHeight;y=p/2;f=N/2;var O=V/
2,aa=Q/2,ca,X,Y;K=0;var fa=ra("ABABAB",50),E=za("ABABAB",70),a=wa("ABABAB",100),E=wa(E,100),fa=wa(fa,100),ha,S={isFirst:!0},M={},pa,qa,ia,na;if(v&&(d=v.colorArr)&&1<(h=d.length)){S.toolText=pa=t=v.scaleMin;M.toolText=qa=v=v.scaleMax;da=v-t;S.snapPX=M.snapPX=0;S.tooltipConstraint=M.tooltipConstraint="chart";S.getLabelConfig=M.getLabelConfig=Ja;S.tooltipPos=[0,0];M.tooltipPos=[0,0];M.tooltipOffsetReference=S.tooltipOffsetReference={};M.tooltipOffsetReference.left=S.tooltipOffsetReference.left+=n-20;
M.tooltipOffsetReference.top=S.tooltipOffsetReference.top+=C;ia=w.colorBox=m.group("colorBox",b);if(I){S.tooltipPos[0]=M.tooltipPos[0]=q+n;K=270;u.angle=90;n=J-V;q=J+N;C=L-aa;P=L+aa;n=A(J-V)+.5;q=A(J)+.5;C=A(L-aa)+.5;P=A(L+aa)+.5;ca=A(J+N)+.5;Y=A(L-2)+.5;U=A(L+2)+.5;F=A(L)+.5;g=J-O/2;X=A(g-aa)+.5;g=A(g)+.5;y=L-aa/2;aa=A(y+aa)+.5;y=A(y)+.5;R/=2;O=["M",n,C,"L",q,C,q,Y,ca,F,q,U,q,P,n,P,"Z","M",X,y,"L",g,y,"M",X,F,"L",g,F,"M",X,aa,"L",g,aa];aa=["M",n+1,C,"L",n+1,P,"M",X,y-1,"L",g,y-1,"M",X,F-1,"L",g,
F-1,"M",X,aa-1,"L",g,aa-1];y=J+N+r;P=A(y+c)+W;y=A(y)+W;F=J+f;X=h-1;for(c=0;c<h;c+=1)f=d[c],q=(f.maxvalue-t)/da,U=p*q+L,r=A(U)+W,c?(u.ratio+=ma,u.color+=ma,u.alpha+=ma,Ea.push("L",y,r,P,r,"M",y,r),c===X?(g=Ha,r=U+2):(g=ka,r=U)):(Ea.push(y,r,"L",P,r,"M",y,r),g=ya,r=U-2),u.ratio+=100*(q-x),u.color+=ba(f.code,ta),u.alpha+=ba(f.alpha,100),x=q,f.legendItem=m.text(b).attr({text:f.label,x:F,y:r,"text-anchor":g,"vertical-align":ka}).rotate(K,F,r).css(ga),f.legendSymbol=m.text(b).attr({text:f.scaleLabel,x:P,
y:U,"text-anchor":ya,"vertical-align":ka}).css(ga);S.xMin=M.xMin=0;S.xMax=M.xMax=0;S.yMin=M.yMin=0;S.yMax=M.yMax=p;S.x=M.x=0;S.y=0;M.y=p;d=Q+N;h=V}else{S.tooltipPos[1]=M.tooltipPos[1]=g+C;n=A(J-O)+.5;q=A(J+O)+.5;C=A(L-Q)+.5;P=A(L+p)+.5;ca=A(J-2)+.5;g=A(J+2)+.5;X=A(J)+.5;Y=A(L)+.5;U=L-aa/2;F=A(U-aa)+.5;U=A(U)+.5;K=J-O/2;f=A(K+O)+.5;K=A(K)+.5;B/=2;O=["M",n,C,"L",q,C,q,Y,g,Y,X,P,ca,Y,n,Y,"Z","M",K,F,"L",K,U,"M",X,F,"L",X,U,"M",f,F,"L",f,U];aa=["M",n,C+1,"L",q,C+1,"M",K-1,F,"L",K-1,U,"M",X-1,F,"L",X-
1,U,"M",f-1,F,"L",f-1,U];r=L+p+r;K=A(r+c)+W;r=A(r)+W;U=L+y;X=h-1;for(c=0;c<h;c+=1)f=d[c],q=(f.maxvalue-t)/da,P=N*q+J,y=A(P)+W,c?(u.ratio+=ma,u.color+=ma,u.alpha+=ma,Ea.push("L",y,r,y,K,"M",y,r),c===X?(g=ya,y=P+2):(g=ka,y=P)):(Ea.push(y,r,"L",y,K,"M",y,r),g=Ha,y=P-2),u.ratio+=100*(q-x),u.color+=ba(f.code,ta),u.alpha+=ba(f.alpha,100),x=q,f.legendItem=m.text(b).attr({text:f.label,x:y,y:U,"text-anchor":g,"vertical-align":ka}).css(ga),f.legendSymbol=m.text(b).attr({text:f.scaleLabel,x:P,y:K,"text-anchor":ka,
"vertical-align":Ga}).css(ga);S.xMin=M.xMin=0;S.xMax=M.xMax=N;S.yMin=M.yMin=0;S.yMax=M.yMax=0;S.y=M.y=0;S.x=0;M.x=N;d=V;h=Q+p}w.colorBox=m.rect(ia).attr({x:J,y:L,width:N,height:p,fill:sa(H),stroke:oa,strokeWidth:Oa});z&&(w.colorBoxEffect=m.rect(ia).attr({x:J,y:L,width:R,height:B,fill:e,"stroke-width":0}));w.scale=m.path(b).attr({path:Ea,stroke:La,"stroke-width":ea});ha=function(a,c,d,b,h){var f;I?(f=c*da/p+t,b=0<c?b:b+c+.01):(f=a*da/N+t,d=0<a?d:d+a+.01);a=Ba(f);h?(w.slider1.translate(d,b),w.slider1Effect.translate(d,
b),w.slider1Tracker.toFront().translate(d,b).tooltip(a,null,null,!0),pa=f):(w.slider2.translate(d,b),w.slider2Effect.translate(d,b),w.slider2Tracker.toFront().translate(d,b).tooltip(a,null,null,!0),qa=f);k&&(na=clearTimeout(na),na=setTimeout(function(){D.setScaleRange&&D.setScaleRange(pa,qa)},100))};z=function(a,c){var d=0,b=d,h,f=this.isFirst,e=f?M:S;if(I){b=this._startY+c;0>=b&&(b=0);b>p&&(b=p);if(f?b>e.y:b<e.y)b=e.y;Ia(b-this.y)>=(this.snapPX||0)&&(h=!0)}else{d=this._startX+a;0>=d&&(d=0);d>N&&
(d=N);if(f?d>e.x:d<e.x)d=e.x;Ia(d-this.x)>=(this.snapPX||0)&&(h=!0)}h&&(ha(d,b,d-this.x,b-this.y,f),this.x=d,this.y=b)};R=function(){var a=this.isFirst;this._startX=this.x;this._startY=this.y;this._scaleStart=pa;this._scaleEnd=qa;la.raiseEvent("LegendPointerDragStart",{pointerIndex:a?0:1,pointers:[{value:pa},{value:qa}],legendPointerHeight:Q,legendPointerWidth:V},D.logic.chartInstance)};B=function(){var a=this._scaleStart,c=this._scaleEnd;la.raiseEvent("LegendPointerDragStop",{pointerIndex:this.isFirst?
0:1,pointers:[{value:pa},{value:qa}],legendPointerHeight:Q,legendPointerWidth:V},D.logic.chartInstance);a===pa&&c===qa||la.raiseEvent("LegendRangeUpdated",{previousMinValue:a,previousMaxValue:c,minValue:pa,maxValue:qa},D.logic.chartInstance);delete this._scaleStart;delete this._scaleEnd};H=Ba(t);w.slider1=m.path(b).attr({path:O,fill:a,strokeWidth:1,stroke:E});w.slider1Effect=m.path(b).attr({path:aa,fill:"none",strokeWidth:1,stroke:fa});Aa&&(n-=.5*(T(30,d)-d),C-=.5*(T(40,h)-h),d=T(30,d),h=T(40,h));
w.slider1Tracker=m.rect(b).attr({ishot:!0,width:d,height:h,x:n,y:C,fill:Ka,stroke:"none"}).drag(z,R,B,S,S,S).tooltip(H,null,null,!0).css(l);H=Ba(v);w.slider2=m.path(b).attr({path:O,fill:a,strokeWidth:1,stroke:E}).translate(M.x,M.y);w.slider2Effect=m.path(b).attr({path:aa,fill:"none",strokeWidth:1,stroke:fa}).translate(M.x,M.y);w.slider2Tracker=m.rect(b).attr({ishot:!0,width:d,height:h,x:n,y:C,fill:Ka,stroke:"none"}).translate(M.x,M.y).css(l).drag(z,R,B,M,M,M).tooltip(H,null,null,!0)}}}]);
FusionCharts.register("module",["private","modules.renderer.js-maps",function(){var V=this,fa=V.window,D=V.hcLib,O=D.chartAPI,la=fa.document,b=D.pluck,va=D.imprint,G=D.extend2,ta=D.parseTooltext,e=D.pluckNumber,Da=D.pluckFontSize,xa=D.HCstub,Fa=G(D.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",backgroundlightalpha:"100",backgroundlightangle:90,
backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),ja=D.setLineHeight,ua=D.getValidValue,ia=D.parseUnsafeString,ma=D.getFirstColor,Z=D.graphics.convertColor,Y=D.hashify,wa=D.getDashStyle,Ga=fa.navigator.userAgent,ka=/msie/i.test(Ga)&&!fa.opera,ya=/AppleWebKit/.test(Ga),Ha=/stroke/ig,za=D.hasSVG,ra=D.FC_CONFIG_STRING,ba=fa.Math,ca=ba.min,sa=ba.max,Aa=ba.ceil,A=D.toRaphaelColor,
T={left:"start",right:"end",center:"middle"},Q=function(d,c){var b;d||(d={});for(b in c)d[b]=c[b];return d},Ia=function(d){var c=this.parentNode;if(!c)return!1;for(;c&&c!==la.documentElement;){if(c===d)return!0;c=c.parentNode}return!1},W=function(d,c){var b=c?Q(d.FCcolor,c):{FCcolor:d};b.toString=A;return b},Ja=function(d,c){var b,f;this.index=c;for(f in d)b=Fa[d[f]],this[f]=b instanceof Array?b[c]:b},Ba={right:function(d,c){return c},left:function(d,c){return d-c},center:function(d,c){return 2*ca(c,
d-c)}},Ka={top:function(d,c){return c},middle:function(d,c){return 2*ca(c,d-c)},bottom:function(d,c){return d-c}},Ca=function(d,c,b,f){c=ca(d,c);d=.02*c;c*=.07;f=parseFloat(f);b=parseFloat(b);return isNaN(f)||isNaN(b)?isNaN(f)?isNaN(b)?{min:d,max:c}:{min:parseInt(b/10,10),max:b}:{min:f,max:10*f}:f<b?{min:f,max:b}:{min:b,max:f}},Na=function(d){for(var c=d&&d.length||0,b={},f;c--;)f=d[c],void 0!==f.id&&(b[f.id.toLowerCase()]=f);return b},Ma=function(d,c){var b,f={};c=c||1;if(!d||"object"!==typeof d)return f;
for(b in d)Ha.test(b)||("stroke-width"===b?(f[b]=Number(d[b])/c,ya&&(f[b]=f[b]&&Aa(f[b])||0)):f[b]=d[b]);return f},m=function(){this.hoverEntity&&(D.raiseEvent.apply(D,this.hoverEntityEventArgs),delete this.hoverEntityEventArgs,this.hoverEntity&&this.hoverEntityAttr&&this.hoverEntity.attr(this.hoverEntityAttr),delete this.hoverEntityAttr,this.hoverEntity=null)},l=function(d,c){var b=d&&d.length||!1,f=c||"id",a={},e;if(!d)return d;for(;b--;)e=d[b],void 0!==e[f]&&(a[e[f].toLowerCase()]=e);return a},
n=function(d,c,b,f){function a(){var a=this,c=a.entityPathMap,d=a.data,b=a.items,h,d=Na(d);x=function(){for(var f,k=c[h];k;)b[h]?a=null:((f=d[h])?f.mapItem=b[h]=new C(h,va(e(f),k),t,a.group):b[h]=new C(h,k,t,a.group),h=k.nextId&&k.nextId.toLowerCase(),k=void 0!==h&&c[h]||null);w.call(a)};z=function(){var h,f,k=r,x,g=0;for(x in l)if(!b[x]&&(h=c[x],(f=d[x])?f.mapItem=b[x]=new C(x,va(e(f),h),t,a.group):b[x]=new C(x,h,t,a.group),g+=1,delete l[x],g===k))break;g<P?(P-=g,setTimeout(z,0)):w.call(a)};(h=I&&
I.toLowerCase())?x():z()}function e(a){delete a.outlines;delete a.label;delete a.shortlabel;delete a.labelposition;delete a.labelalignment;delete a.labelconnectors;return a}function g(){var a=this.items,c=[],d,b={id:"entityLabels",items:c};for(d in a)a[d].drawLabel(c);n.addGroup(b)}function k(){var a=this.items,c;for(c in a)a[c].destroy();delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group}function w(){y.entities.labelsOnTop&&g.call(this);this.ready=
!0;t.checkComplete()}if(b&&b.getEntityPaths()){var I=b.getFirstId(),P=b.entityCount,l=b.getEntityPaths(!0),t=c,n=c.mapAnnotations,y=t.options,r=ka?50:0,x,z,R;this.entityPathMap=l;this.data=d;this.chartObj=t;this.items={};this.ready=!1;this.group=f||c.mapGroup;this.isReady=function(){return this.ready};a.call(this);this.drawLabels=g;this.destroy=k;this.init=a;this.initComplete=w;t.__canvasMouseOutListenerAdded||(t.__canvasMouseOutListenerAdded=!0,R=c.paper.canvas,D.addEvent(R,"mouseout",function(a){a=
a.originalEvent.relatedTarget||a.originalEvent.toElement;!ka||za?a&&a.ownerSVGElement&&a.ownerSVGElement===R||m.call(t):a===la.documentElement||a===c.container||a===c.container.parentElement?m.call(t):Ia.call(a,R)||m.call(t)}))}},C=function(d,c,h,f){function a(a){var c=this.featureConfig;return c&&"undefined"!==typeof c[a]?Boolean(c[a]):!1}function E(){var d;if(a.apply(this,["_ds"])){d=c.labels&&c.labels[0];if(!d)return;d=(p.useSNameInTooltip?d.shortText:d.text)+(isNaN(u)?"":p.tooltipSepChar+q)}else d=
(p.useSNameInTooltip?c.shortLabel:c.label)+(isNaN(u)?"":p.tooltipSepChar+q);return d}function g(a,d,h){d?h&&"undefined"!==typeof c.displayvalue?a=c.displayvalue:(a=b(p.includeNameInLabels?p.useShortName?a.shortText:a.text:""),p.includeValueInLabels&&!isNaN(u)&&(a=void 0===a?q:a+L+q)):a=a.text;return a}function k(a){for(var c=a&&a.length||0,d;c--;)d=a[c],this.connectorElem[c]=N.path(d,this.group).attr({transform:na.transform,stroke:Z(T,Q),"shape-rendering":"crisp","stroke-width":O})}function w(){var a=
this.chart.paper,c=za||!ka?"litepath":"path",d=this.eJSON.outlines,b=this.group,f,e,k;f=d&&d.length||0;if(this.hasFeature("_ds")){if(this.hasFeature("isDataEnabled"))if(pa)for(;f--;)e=d[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[c](e,b).attr(na).tooltip(K).shadow(ma,h.shadowLayer);else for(;f--;)e=d[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[c](e,b).tooltip(K).attr(na);else if(pa)for(;f--;)k=G(G({},na),Ma(d[f].style,la)),e=d[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=
a[c](e,b).attr(k).tooltip(K).shadow(ma,h.shadowLayer);else for(;f--;)k=G(G({},na),Ma(d[f].style,la)),e=d[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[c](e,b).tooltip(K).attr(k);this.hasFeature("isDataEnabled")&&this.addMouseGestures()}else{if(pa)for(;f--;)e=d[f],this.svgElems[f]={},this.svgElems[f].graphic=a[c](e,b).attr(na).tooltip(K).shadow(ma,h.shadowLayer);else for(;f--;)e=d[f],this.svgElems[f]={},this.svgElems[f].graphic=a[c](e,b).tooltip(K).attr(na);this.addMouseGestures()}return this}
function I(a){var c=this.chart;c.hoverEntityEventArgs=["entityrollout",this.eventArgs,c.fusionCharts,[c.fusionCharts.id,"rollOut",this.legacyEventArgs],a];ja&&this.isVisible&&(c.hoverEntity=this,c.hoverEntityAttr=this.revertAttr,this.attr(this.hoverAttr));D.raiseEvent("entityrollover",this.eventArgs,c.fusionCharts,[c.fusionCharts.id,"rollOver",this.legacyEventArgs],a)}function P(a,c,d){var b=this,f=b.chart,e=a.labelPosition,k=a.labelAlignment,E=b.svgElems[0]&&b.svgElems[0].graphic,p=a.style,x,z,w,
B,u;e?(E=e[0],e=e[1]):(e=E.getBBox(),E=e.x+e.width/2,e=e.y+e.height/2);k?(x=k[0],k=k[1],"right"===x?E-=X:"left"===x&&(E+=X),"top"===k?e-=X:"bottom"===k&&(e+=X)):(x="center",k="middle");z=ca;w=parseFloat(aa)/h.sFactor;B=Y;u=S;!c&&p&&(p.color&&(z=p.color),p["font-size"]&&(w=parseFloat(p["font-size"])/h.sFactor),p["font-family"]&&(B=p["font-family"]),void 0!==p["font-weight"]&&(u="bold"===p["font-weight"]));return{x:E.toString(),y:e.toString(),wrapwidth:Ba[x](ua,E+wa)-X,wrapheight:Ka[k](va,e+xa)-X,wrap:1,
type:"text",align:x,valign:k,text:g(a,c,d),tooltext:K,link:M,bgcolor:"",bordercolor:"",fillcolor:z,fontsize:w,font:B,bold:u,onclick:function(a){V.raiseEvent("entityclick",b.eventArgs,h.fusionCharts,a)},onmouseover:function(a){b!==f.hoverEntity&&(m.call(b.chart),I.call(b,a))},ontouchstart:function(a){b!==f.hoverEntity&&(m.call(b.chart),I.call(b,a))}}}function l(a){var c=this.eJSON,d=this.hasFeature("isDataEnabled"),b,f;if(!La)return null;if(this.hasFeature("_ds"))for(f=(c=c.labels)&&c.length||0;f--;)b=
c[f],a.push(this.getLabelObject(b,d,!f)),b.labelConnectors&&this.drawLabelConnectors(b.labelConnectors);else b={text:c.label,shortText:c.shortLabel,labelAlignment:c.labelAlignment,labelPosition:c.labelPosition},a.push(this.getLabelObject(b,!0,!0)),c.labelConnectors&&this.drawLabelConnectors(c.labelConnectors)}function t(a,c){var d=this.svgElems,b;for(b in d)d[b].graphic&&d[b].graphic.attr(a,c)}function n(){var a=this.svgElems,c;this.isVisible=!0;for(c in a)a[c].graphic&&a[c].graphic.attr(na)}function y(){var a=
this.svgElems,c=this.chart,d;this.isVisible=!1;c.hoverEntity===this&&m.call(c);for(d in a)a[d].graphic&&a[d].graphic.attr(qa)}function r(a){V.raiseEvent("entityclick",this.node.__entity.eventArgs,h.fusionCharts,a);void 0!==M&&h.logic.linkClickFN.call({link:M})}function x(a){var c=this.node.__entity,d=c.chart;c!==d.hoverEntity&&(m.call(d),I.call(c,a))}function z(){var a=this.eJSON,c=this.svgElems,d;this.eventArgs={value:this.value,label:a.label,shortLabel:a.shortLabel,originalId:this.originalId||this.id,
id:this.id};this.legacyEventArgs={value:this.value,lName:a.label,sName:a.shortLabel,id:this.originalId||this.id};ja&&(this.hoverAttr={fill:this.hoverColor.toString()},this.revertAttr={fill:this.fillColor.toString()},ha!==ea&&(this.hoverAttr["stroke-width"]=ha,this.revertAttr["stroke-width"]=ea));if(!isNaN(u)||fa)for(d in c)void 0!==M&&c[d].graphic.css({cursor:"pointer",_cursor:"hand"}),c[d].graphic.node.__entity=this,c[d].graphic.click(r).hover(x)}function R(){var a=this.svgElems,c=this.connectorElem,
d;for(d in a)a[d].remove&&a[d].remove();for(d in c)c[d].destroy&&c[d].destroy();delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;delete this.renderer;delete this.options}if(c&&h&&void 0!==d){this.chart=h;this.eJSON=c;this.group=f;this.id=d;this.originalId=c.origId;this.isVisible=!0;this.svgElems={};this.connectorElem=
{};this.featureConfig=c.options;"object"===typeof this.featureConfig&&(this.featureConfig._ds=!0);var B=h.options,N=h.paper,p=B.entities,H=p.dataLabels.style;d=c.cleanValue;var u=null===d?void 0:d,q=this.formattedValue=c.formattedValue||"",L=p.labelSepChar,F=e(c.showtooltip,p.showTooltip);d=E.call(this);f={formattedValue:q,sName:c.shortLabel,lName:c.label};var K=F?ia(b(ta(b(c.tooltext,p.tooltext,d),[1,2,7,38,39],f,c))):"",v,C,A,La=e(c.showlabel,p.showLabels);f=b(c.bordercolor,p.borderColor);d=b(c.borderalpha,
p.borderAlpha);var F=1===p.scaleBorder,ea=e(c.borderthickness,p.borderThickness),T=b(c.labelconnectorcolor,p.connectorColor),Q=b(c.labelconnectoralpha,p.connectorAlpha),O=e(c.labelconnectorthickness,p.connectorThickness),Y=b(c.font,H.fontFamily),aa=e(parseInt(c.fontsize,10),parseInt(H.fontSize,10)),ca=b(c.fontcolor,H.color),X=e(c.labelpadding,p.labelPadding),fa=p.hoverOnNull,ja=e(c.showhovereffect,c.usehovercolor,fa?p.showHoverEffect:isNaN(u)?0:p.showHoverEffect),ha=e(c.borderhoverthickness,c.hoverborderthickness,
p.hoverBorderThickness),S=e(c.fontbold,0),M=c.link,pa=p.shadow;A=!ka||za;H=h.sFactor/p.baseScaleFactor;v=h.strokeWidth;C=(A?p.baseScaleFactor:1)*v;var qa=p.hiddenEntityFillObject||(p.hiddenEntityFillObject={fill:W({color:p.hiddenEntityColor,alpha:p.hiddenEntityAlpha}).toString()}),la,na,ma,B=B[ra],ua=B._labelBaseWidth,va=B._labelBaseHeight,wa=B._labelXOffset,xa=B._labelYOffset;A?(ea=F?ea*C:ea/H,O/=H,la=F?H:h.sFactor,ya&&(ea=ea&&Aa(ea)||0,O=O&&Aa(O)||0)):(ea=F?ea*v:ea,la=F?h.scaleFactor:p.baseScaleFactor);
p.showHiddenEntityBorder||(qa["stroke-width"]=0);void 0===ha?ha=ea:A?(ha=F?ea*C:ha/H,ya&&(ha=ha&&Aa(ha)||0)):ha=F?ha*v:ha;!p.showNullEntityBorder&&isNaN(u)&&(ea=0);void 0!==b(c.color,c.alpha,c.angle,c.ratio)?(F=b(c.color,p.fillColor),B=b(c.alpha,p.fillAlpha),v=b(c.angle,p.fillAngle),C=b(c.ratio,p.fillRatio),A=W({color:F,alpha:B,angle:v,ratio:C})):(p.fillColorObject||(p.fillColorObject=W({color:b(p.fillColor),alpha:b(p.fillAlpha),angle:b(p.fillAngle),ratio:b(p.fillRatio)})),p.emptyColorObject||(p.emptyColorObject=
W({color:b(p.nullEntityColor),alpha:b(p.nullEntityAlpha),angle:b(p.nullEntityAngle),ratio:b(p.nullEntityRatio)})),A=isNaN(u)?p.emptyColorObject:p.fillColorObject,F=A.FCcolor.color,B=A.FCcolor.alpha,v=A.FCcolor.angle,C=A.FCcolor.ratio);""===K&&(F=0);na={transform:za||!ka?"":h.transformStr,stroke:Z(f,d),"stroke-width":ea,fill:(this.fillColor=A).toString()};f=B.split(",");ea&&f.push(d);ma={scalefactor:[H,h.sFactor],opacity:sa.apply(ba,f)/100};ja&&(void 0!==b(c.fillhovercolor,c.fillhoveralpha,c.fillhoverangle,
c.fillhoverratio,c.hoverfillcolor,c.hoverfillalpha,c.hoverfillratio,c.hoverfillangle)?(F=b(c.fillhovercolor,c.hoverfillcolor,p.hoverFillColor),B=b(c.fillhoveralpha,c.hoverfillalpha,p.hoverFillAlpha),v=b(c.fillhoverangle,c.hoverfillangle,p.hoverFillAngle),C=b(c.fillhoverratio,c.hoverfillratio,p.hoverFillRatio),d=W({color:F,alpha:B,angle:v,ratio:C})):(p.hoverColorObject||(p.hoverColorObject=W({color:p.hoverFillColor,alpha:p.hoverFillAlpha,angle:p.hoverFillAngle,ratio:p.hoverFillRatio})),d=p.hoverColorObject),
this.hoverColor=d);this.value=u;this.addMouseGestures=z;this.attr=t;this.draw=w;this.drawLabel=l;this.getLabelObject=P;this.destroy=R;this.show=n;this.hide=y;this.hasFeature=a;this.drawLabelConnectors=k;w.call(this);p.hideNullEntities&&void 0===u&&this.hide()}},q=function(d,c,b,f){this.id=d;this.definition=c;this.application=b;this.rapi=f;this.markerLabel=this.markerShape=this.label=this.options=this.value=this.hasValue=null;this.drawOptions={shape:null,label:null};this.drawComplete=!1;if(d=f.options)this._conf=
d[ra];this.init()},g=function(d,c,b,f){this.options=d;this.from=c;this.to=b;this.api=f;if(d=f.options)this._conf=d[ra]},v=function(d,c){function h(){var d=I.definition,b=l(d)||{},f=l(I.application)||{},h=I.shapes,k,p;if(d&&d.length){if(h&&h.length)for(d=h.length;d;--d)if(k=h[d-1],p=k.id.toLowerCase())a[p]=k;for(p in b){k=b[p];h=new q(p,k,f[p],c);if(d=h.getShapeId())h.shapeObj=a[d];e[p]=h}}}function f(){var d=I.items,b=I.shapes,f,h,k,p;if(d&&d.length){if(b&&b.length)for(f=b.length;f;--f)if(h=b[f-1],
p=h.id.toLowerCase())a[p]=h;for(f=d.length;f--;)if(h=d[f],p=h.id&&h.id.toLowerCase())void 0!==h.value&&""!==h.value&&parseFloat(h.value),h.mapItem=b=new q(p,h,null,c),k=b.getShapeId(),h.__hideMarker&&(b._isHidden=!0),k&&(b.shapeObj=a[k]),e[p]=b}}var a={},e={},ga=[],k=c.options.markers,w=c.options.connectors,I=d,m=c.mapAnnotations,n,t,da,y,r=[];this.items=e;(function(){var a=q.prototype,d=g.prototype,f;f=Boolean(b(k.hoverFillColor,k.hoverFillAlpha,k.hoverFillAngle,k.hoverFillRatio,k.hoverBorderThickness,
k.hoverBorderColor,k.hoverBorderAlpha));a.markerFont=k.dataLabels.style.fontFamily;a.markerFontSize=k.dataLabels.style.fontSize;a.markerFontColor=k.dataLabels.style.fontColor;a.showMarkerTooltip=k.showTooltip;a.showHoverEffect=f;a.tooltext=k.tooltext;a.showMarkerLabels=k.showLabels;a.markerLabelPadding=k.labelPadding;a.labelWrapWidth=k.labelWrapWidth;a.labelWrapHeight=k.labelWrapHeight;a.labelSepChar=k.labelSepChar;a.tooltipSepChar=k.tooltipSepChar;a.fillColor=k.fillColor;a.fillAlpha=k.fillAlpha;
a.fillRatio=k.fillRatio;a.fillAngle=k.fillAngle;a.hoverFillColor=k.hoverFillColor;a.hoverFillAlpha=k.hoverFillAlpha;a.hoverFillRatio=k.hoverFillRatio;a.hoverFillAngle=k.hoverFillAngle;a.startAngle=k.startAngle;a.shapeId=k.shapeId;a.borderThickness=k.borderThickness;a.borderColor=k.borderColor;a.borderAlpha=k.borderAlpha;a.hoverBorderThickness=k.hoverBorderThickness;a.hoverBorderColor=k.hoverBorderColor;a.hoverBorderAlpha=k.hoverBorderAlpha;a.markerRadius=k.radius;a.autoScale=k.autoScale?c.sFactor:
1;a.shadow=k.shadow;a.applyAll=k.applyAll;a.dataEnabled=k.dataEnabled;a.valueToRadius=k.valueToRadius;a=Boolean(b(w.hoverthickness,w.hovercolor,w.hoveralpha));d.showHoverEffect=a;d.showTooltip=w.showTooltip;d.tooltext=w.tooltext;d.thickness=w.thickness;d.color=w.color;d.alpha=w.alpha;d.hoverThickness=w.hoverthickness;d.hoverColor=w.hovercolor;d.hoverAlpha=w.hoveralpha;d.dashed=w.dashed;d.dashlen=w.dashLen;d.dashgap=w.dashGap;d.font=w.font;d.fontsize=w.fontSize;d.fontcolor=w.fontColor;d.bgcolor=w.labelBgColor;
d.bordercolor=w.labelBorderColor;d.shadow=w.shadow;d.hideOpen=w.hideOpen})();k.dataEnabled?f():h();(function(){var d=e,c=[],b,f,h,k;n=m.addGroup({fillalpha:"100",items:c});t=m.addGroup({items:[]});for(k in d)b=null,f=d[k],h=f.getShapeId(),f&&!f._isHidden&&(h&&(f.shapeObj=a[h]),b=f.draw()),b&&(f._annotationIndex=c.length,f.markerShape=b.markerShape&&n.addItem(b.markerShape),f.markerLabel=b.markerLabel&&t.addItem(b.markerLabel))})();(function(){var a=w.showLabels,d=I.connectors,b=d&&d.length,f=[],h=
[],k,m,u;if(b)for(r.push({id:"connectorLabels",fillalpha:"100",items:h}),r.push({id:"connectors",fillalpha:"100",items:f});b--;)if(u=d[b],u.from&&u.to&&(k=e[u.from.toLowerCase()],m=e[u.to.toLowerCase()],k&&m&&(!w.hideOpen||!k._isHidden&&!m._isHidden)&&(ga.push(m=new g(u,k,m,c)),m.connectJSON=k=m.computeConnectorJSON())))f.push(k),k.label&&a&&h.push(m.getLabelJSON())})();y=r.length;for(c.internalAnnotations={};y--;)da=r.shift(),da.id?c.internalAnnotations[da.id]=m.addGroup(da):m.addGroup(da);this.addMarkerItem=
function(d){var b,f;if((b=d.id.toLowerCase())&&!e[b]){delete d.value;d=new q(b,d,null,c);if(f=d.getShapeId())d.shapeObj=a[f];e[b]=d;b=d.draw();n&&t&&(d.markerShape=b.markerShape&&n.addItem(b.markerShape,!0),d.markerLabel=b.markerLabel&&t.addItem(b.markerLabel,!0))}}};g.prototype={constructor:g,computeConnectorJSON:function(){var d=this.api,c=this.options,h=this.from,f=this.to,a=c.link,E=c.label,g=e(c.showtooltip,this.showTooltip),k=g?b(c.tooltext,this.tooltext):"",w=b(c.thickness,this.thickness),
I=b(c.color,this.color),l=b(c.alpha,this.alpha),n=e(c.showhovereffect,this.showHoverEffect),t=b(c.hovercolor,this.hoverColor,I),q=b(c.hoveralpha,this.hoverAlpha,l),y=b(c.hoverthickness,this.hoverThickness,w),r=b(c.dashed,this.dashed),x=e(c.dashlen,this.dashlen),z=e(c.dashgap,this.dashgap),v;k&&(this.tooltext=k=ia(ta(k,[3,40,41,42,43],{label:E,fromId:h.definition.id,toId:f.definition.id,fromLabel:h.definition.label,toLabel:f.definition.label},c)));return h&&f?(v={fromMarkerId:h.id,toMarkerId:f.id,
label:E},G({type:"line"},{x:h.definition.x,y:h.definition.y,tox:f.definition.x,toy:f.definition.y,dashed:r,dashlen:x,dashgap:z,link:a,tooltext:g?k:"",thickness:w,color:I,alpha:l,label:E,showshadow:this.shadow,_hovereffect:n,_defaultattrs:{stroke:W({color:I,alpha:l}).toString(),"stroke-width":w},_hoverattrs:{stroke:W({color:t,alpha:q}).toString(),"stroke-width":y},onmouseover:function(a){var c=a.data,b=c.wrapper;b&&c.options._hovereffect&&(m.call(d),b.attr(c.options._hoverattrs));V.raiseEvent("connectorrollover",
v,d.fusionCharts,a)},onmouseout:function(a){var c=a.data,b=c.wrapper;b&&c.options._hovereffect&&b.attr(c.options._defaultattrs);V.raiseEvent("connectorrollout",v,d.fusionCharts,a)},onclick:function(a){V.raiseEvent("connectorClick",v,d.fusionCharts,a)}})):null},getLabelJSON:function(){var d=this.connectJSON;return G({type:"text"},{x:((Number(d.x)+Number(d.tox))/2).toString(),y:((Number(d.y)+Number(d.toy))/2).toString(),text:d.label,align:"center",valign:"middle",font:this.font,fontsize:this.fontsize/
this.api.sFactor,fillcolor:this.fontcolor,bgcolor:this.bgcolor,bordercolor:this.bordercolor,tooltext:this.tooltext})}};q.prototype={constructor:q,init:function(){var d;d=this.options=G({},this.definition);this.dataEnabled?isNaN(d.value)||""===d.value||(this.value=parseFloat(d.value),this.hasValue=!0):this.applyAll?this.options=G(d,this.application):this.application&&(this.options=G(d,this.application))},getShapeId:function(){return this.options.shapeid&&this.options.shapeid.toLowerCase()||this.shapeId},
getLabelOptions:function(d,c,b,f,a){var e,g=d&&d.toLowerCase();this.getLabelAlignment[g]||(g="center");d=Number(b.x);e=Number(b.y);b=void 0===f||void 0===a?b.radius||0:/^(top|bottom)$/ig.test(g)&&.5*a||/^(left|right)$/ig.test(g)&&.5*f||0;b=Number(b)+Number(c);return this.getLabelAlignment[g](d,e,b)},draw:function(){if(this.options){var d=this.rapi,c=this._conf,h=d.translateX,f=d.translateY,a=this.options,E=this.getShapeId(),g=a.scale||1,k=a.label||"",w=(a.labelpos||"top").toLowerCase(),I=void 0===
a.formattedValue?void 0:a.formattedValue,l=a.tooltext||this.tooltext,n=e(a.radius,this.markerRadius)*g*this.autoScale||1E-4,t=b(a.fillcolor,a.color,this.fillColor),q=b(a.fillalpha,a.alpha,this.fillAlpha),y=b(a.fillratio,this.fillRatio),r=b(a.fillangle,this.fillAngle),x=e(a.borderthickness,this.borderThickness),z=b(a.bordercolor,this.borderColor),v=b(a.borderalpha,this.borderAlpha),B=a.labelpadding||this.markerLabelPadding;if(E){l=l?ia(ta(l,[1,2,3],{formattedValue:I,label:k},a)):I?k+this.tooltipSepChar+
I:k;void 0!==I&&null!==I?k=k+this.labelSepChar+I:isNaN(g)?g=1:0>g?g=0:5<g&&(g=5);a={x:a.x.toString(),y:a.y.toString(),fillcolor:t,fillalpha:q,fillratio:y,fillangle:r,borderthickness:x,bordercolor:z,borderalpha:v,hovereffect:b(a.showhovereffect,this.showHoverEffect),radius:n.toString(),tooltext:this.showMarkerTooltip?l:"",link:a.link,showshadow:e(a.showshadow,this.shadow),_markerLabel:k,_markerId:a.id,id:(a.id+"").toLowerCase(),onmouseover:function(a){var c=a.data,b=c.options,e=c.bounds,k=b._markerEventArgs;
(c=c.wrapper)&&b.hovereffect&&(m.call(d),c.attr(b._hoverattrs));k||(k=b._markerEventArgs={x:e.x1/e.xs,y:e.y1/e.ys,scaledX:e.x1,scaledY:e.y1,chartX:h+e.x1,chartY:f+e.y1,id:b._markerId,label:b._markerLabel});V.raiseEvent("markerRollOver",k,d.fusionCharts,a)},onmouseout:function(a){var c=a.data,b=c.wrapper;b&&c.options.hovereffect&&b.attr(c.options._defaultattrs);V.raiseEvent("markerRollOut",c.options._markerEventArgs,d.fusionCharts,a)},onclick:function(a){V.raiseEvent("markerClick",a.data.options._markerEventArgs,
d.fusionCharts,a)}};"triangle"===E?G(a,{type:"polygon",sides:3,startangle:this.startAngle}):"diamond"===E?G(a,{type:"polygon",sides:4,startangle:this.startAngle}):"arc"===E?G(a,{type:"arc",startangle:0,endangle:360,innerradius:.6*n}):"circle"===E?a.type="circle":(B=this.getShapeArgs(),this.dataEnabled&&this.valueToRadius&&void 0!==a.radius?delete B.radius:(!B.radius&&(B.radius=this.markerRadius),B.radius=B.radius*g*this.autoScale),G(a,B));G(a,{hoverfillcolor:b(a.fillhovercolor,this.hoverFillColor,
a.fillcolor),hoverfillalpha:b(a.fillhoveralpha,this.hoverFillAlpha,a.fillalpha),hoverfillratio:b(a.fillhoverratio,this.hoverFillRatio,a.fillratio),hoverfillangle:b(a.fillhoverangle,this.hoverFillAngle,a.fillangle),hoverborderthickness:e(a.borderhoverthickness,this.hoverBorderThickness,a.borderthickness),hoverbordercolor:b(a.borderhovercolor,this.hoverBorderColor,a.bordercolor),hoverborderalpha:b(a.borderhoveralpha,this.hoverBorderAlpha,a.borderalpha)});a._defaultattrs={fill:W({alpha:a.fillalpha,color:a.fillcolor,
angle:a.fillangle,ratio:a.fillratio}).toString(),"stroke-width":"0"!==a.showborder?a.borderthickness:0,stroke:Z(a.bordercolor,a.borderalpha)};a._hoverattrs={fill:W({alpha:a.hoverfillalpha,color:a.hoverfillcolor,angle:a.hoverfillangle,ratio:a.hoverfillratio}).toString(),"stroke-width":"0"!==a.showborder?a.hoverborderthickness:0,stroke:Z(a.hoverbordercolor,a.hoverborderalpha)};"image"===a.type&&(a.borderthickness=a.borderthickness||0,a.onload=function(a){var c=this.options,b=a.width;a=a.height;var f=
(Number(c.x)-b/(2*d.sFactor))*d.sFactor,c=(Number(c.y)-a/(2*d.sFactor))*d.sFactor,h;if(b&&a)for(h in{wrapper:1,tracker:1})this[h]&&this[h].attr({x:f,y:c,width:b,height:a})});this.drawOptions.shape=a;if(!this.showMarkerLabels)return{markerShape:a};B=a.labelpadding||this.markerLabelPadding;g=this.getLabelOptions(w,B,a);w=g.align;E=g.valign;l=c._labelBaseWidth;I=c._labelBaseHeight;n=c._labelXOffset;c=c._labelYOffset;l=this.labelWrapWidth?this.labelWrapWidth:this.getWrapWidth[w](l,Number(g.x)+n);c=this.labelWrapHeight?
this.labelWrapHeight:this.getWrapHeight[E](I,Number(g.y)+c);l>B&&(l-=B);c>B&&(c-=B);this.drawOptions.label=G({type:"text"},{text:k,tooltext:a.tooltext,x:g.x,y:g.y,align:w,valign:g.valign,wrap:1,wrapwidth:l,wrapheight:c,fontsize:this.markerFontSize/d.sFactor,font:this.markerFont,fillcolor:this.markerFontColor});return{markerShape:a,markerLabel:this.drawOptions.label}}}},show:function(){this.setMarkerVisibility(!0)},hide:function(){this.setMarkerVisibility(!1)},setMarkerVisibility:function(d){var c=
this.rapi&&this.rapi.internalAnnotations;if(c=(c=c&&c.markers)&&c.items)if(c=c[this._annotationIndex])this._origFill||(this._origFill=W({alpha:c.fillAlpha,color:c.fillColor,angle:c.fillAngle,ratio:c.fillRatio}),this._hideFill=W({alpha:"0",color:c.fillColor,angle:c.fillAngle,ratio:c.fillRatio})),d?c.wrapper.attr({fill:this._origFill}):c.wrapper.attr({fill:this._hideFill})},getShapeArgs:function(){var d=G({},this.shapeObj),c;return d?("polygon"===d.type?3>d.sides?d.type="circle":d.startangle=this.startAngle:
"arc"===d.type&&(c=(d.radius||this.markerRadius)*this.autoScale,d.radius=c,d.innerradius=d.innerradius&&d.innerradius*this.autoScale||.6*c),d):null},destroy:function(){var d=this.markerShape,c=this.markerLabel,b;d&&d.destroy();c&&c.destroy();for(b in this)delete this[b]},getLabelAlignment:{top:function(d,c,b){return{x:d.toString(),y:(c-b).toString(),align:"center",valign:"top"}},left:function(d,c,b){return{x:(d-b).toString(),y:c.toString(),align:"right",valign:"middle"}},right:function(d,c,b){return{x:(d+
b).toString(),y:c.toString(),align:"left",valign:"middle"}},bottom:function(d,c,b){return{x:d.toString(),y:(c+b).toString(),align:"center",valign:"bottom"}},center:function(d,c){return{x:d.toString(),y:c.toString(),align:"center",valign:"middle"}}},getWrapWidth:{right:function(d,c){return c},left:function(d,c){return d-c},center:function(d,c){return 2*ca(c,d-c)}},getWrapHeight:{top:function(d,c){return c},middle:function(d,c){return 2*ca(c,d-c)},bottom:function(d,c){return d-c}}};Q(D.eventList,{entityrollover:"FC_Event",
entityrollout:"FC_Event"});O("geo",{name:"geo",friendlyName:"Map",revision:1,creditLabel:!1,standaloneInit:!1,annotationInteractionEvents:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",rendererId:"maps",entities:{},draw:function(d,c){var b=this.renderer,f=this.chartInstance;b||(b=this.renderer=new O("renderer."+this.rendererId));this.updateDefaultAnnotations();f.addEventListener("internal.mapdrawingcomplete",
function(a,d){c&&c.apply(this,[d.renderer]);a.detachHandler()});return b.init(this,d,function(a){a.checkComplete()})},chart:function(d,c){G(this.dataObj.chart,{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,chartbottommargin:this.dataObj.chart.mapbottommargin,chartleftmargin:this.dataObj.chart.mapleftmargin,animation:this.dataObj.chart.animation||"0"});var h=this.dataObj,f=xa(h,d,c,this),a=h.chart,g=h.markers,m=f.chart,k=f[ra],w=m.useRoundEdges=1===
e(a.useroundedges),l=w?1:0,w=w?0:1,n=m.use3DLighting=1===e(a.use3dlighting,1),q=G({},f.tooltip.style),t=new Ja(this.colorPaletteMap,(0<a.palette&&6>a.palette?a.palette:e(this.paletteIndex,1))-1),v=b(a.basefont,"Verdana,sans"),y=Da(a.basefontsize,10),r=b(a.basefontcolor,t.basefontcolor),x=Da(a.outcnvbasefontsize,y),z=b(a.outcnvbasefont,v),C=x+"px",B=Y(b(a.outcnvbasefontcolor,r)),A=b(a.bgcolor,a.canvasbgcolor,t.canvasbgcolor),p=b(a.bgalpha,a.canvasbgalpha,t.canvasbgalpha),H=e(a.usevaluesformarkers,
h.markers&&h.markers.items&&h.markers.items.length,!(h.markers&&h.markers.application&&h.markers.application.length&&h.markers.definition&&h.markers.definition.length)),u,J,L,F,K,O,Q,y=y+"px",r=Y(r);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,f);m.events.click=this.linkClickFN;k.numberFormatter=this.numberFormatter;G(k,{width:d,height:c,showTooltip:e(a.showtooltip,this.showtooltip,1),showHoverEffect:e(a.showhovereffect,1),tooltipSepChar:b(a.tooltipsepchar,", "),
showValues:e(a.showvalues,this.showValues,1),showCanvasBG:b(a.showcanvasbg,1),useValuesForMarkers:H,adjustViewPortForMarkers:e(a.adjustviewportformarkers,H),flatScrollBars:e(a.flatscrollbars,0),scrollBar3DLighting:e(a.scrollbar3dlighting,1),outCanvasStyle:{fontFamily:z,color:B,fontSize:C},inCanvasStyle:{fontFamily:v,fontSize:y,color:r}});ja(k.outCanvasStyle);u=ja(k.inCanvasStyle);k.trendStyle=k.outCanvasStyle;"0"==k.showCanvasBG&&(p="0");J=b(a.entitybordercolor,a.bordercolor,t.plotbordercolor);L=
b(a.entityfillcolor,a.fillcolor,t.plotfillcolor);F=b(a.entityfillalpha,a.fillalpha,t.plotfillalpha);K=b(a.entityfillratio,a.fillratio,t.plotfillratio);O=b(a.entityfillangle,a.fillangle,t.plotfillangle);Q=b(a.nullentityfillcolor,a.nullentitycolor,L);H=e(a.showcanvasborder,w)?e(a.canvasborderthickness,1):0;G(f,{chart:{emulateFlashGutter:e(a._emulateflashgutter,1),defaultSeriesType:this.defaultSeriesType,paletteIndex:t.index,borderRadius:e(a.canvasborderradius,0),borderColor:Z(b(a.canvasbordercolor,
t.canvasbordercolor),b(a.canvasborderalpha,t.canvasborderalpha)),borderWidth:H,borderDashStyle:e(a.canvasborderdashed,0)?wa(e(a.canvasborderdashlen,4),e(a.canvasborderdashgap,2),H):void 0,backgroundColor:W({color:A,alpha:p,angle:b(a.bgangle,a.canvasbgangle,t.canvasbgangle),ratio:b(a.bgratio,a.canvasbgratio,t.canvasbgratio)}),plotBorderColor:"#ffffff",plotBorderWidth:0,plotBackgroundColor:W({color:"#ffffff",alpha:0}),bgSWF:b(a.bgimage,a.bgswf),bgSWFAlpha:e(a.bgimagealpha,a.bgswfalpha,100),bgImageScale:e(a.bgimagescale,
100),bgImageDisplayMode:b(a.bgimagedisplaymode,"none").toLowerCase(),logoURL:ua(a.logourl),logoPosition:b(a.logoposition,"tl").toLowerCase(),logoAlpha:e(a.logoalpha,100),logoLink:ua(a.logolink),logoScale:e(a.logoscale,100),logoLeftMargin:e(a.logoleftmargin,0),logoTopMargin:e(a.logotopmargin,0),toolbar:function(){var f={button:{}},h=f.button,k;h.scale=e(a.toolbarbuttonscale,1.15);h.width=e(a.toolbarbuttonwidth,15);h.height=e(a.toolbarbuttonheight,15);h.radius=e(a.toolbarbuttonradius,2);h.spacing=e(a.toolbarbuttonspacing,
5);h.fill=Z(b(a.toolbarbuttoncolor,"ffffff"));h.labelFill=Z(b(a.toolbarlabelcolor,"cccccc"));h.symbolFill=Z(b(a.toolbarsymbolcolor,"ffffff"));h.hoverFill=Z(b(a.toolbarbuttonhovercolor,"ffffff"));h.stroke=Z(b(a.toolbarbuttonbordercolor,"bbbbbb"));h.symbolStroke=Z(b(a.toolbarsymbolbordercolor,"9a9a9a"));h.strokeWidth=e(a.toolbarbuttonborderthickness,1);h.symbolStrokeWidth=e(a.toolbarsymbolborderthickness,1);k=h.symbolPadding=e(a.toolbarsymbolpadding,5);h.symbolHPadding=e(a.toolbarsymbolhpadding,k);
h.symbolVPadding=e(a.toolbarsymbolvpadding,k);k=f.position=b(a.toolbarposition,"tr").toLowerCase();switch(k){case "tr":case "tl":case "br":case "bl":break;default:k="tr"}h=f.hAlign="left"===(""+a.toolbarhalign).toLowerCase()?"l":k.charAt(1);k=f.vAlign="bottom"===(""+a.toolbarvalign).toLowerCase()?"b":k.charAt(0);f.hDirection=e(a.toolbarhdirection,"r"===h?-1:1);f.vDirection=e(a.toolbarvdirection,"b"===k?-1:1);f.vMargin=e(a.toolbarvmargin,6);f.hMargin=e(a.toolbarhmargin,10);f.x=e(a.toolbarx,"l"===h?
0:d);f.y=e(a.toolbary,"t"===k?0:c);return f}()},title:{text:ia(a.caption),offsetX:Number(a.captionxshift),offsetY:Number(a.captionyshift),position:b(a.captionposition,void 0!==a.captionxshift||void 0!==a.captionyshift?"top left":"top"),padding:e(a.captionpadding,10),style:{fontFamily:b(a.captionfontfamily,z),color:b(a.captionfontcolor,B).replace(/^#?([a-f0-9]+)/ig,"#$1"),fontSize:e(a.captionfontsize,x+3)+"px",fontWeight:0===e(a.captionfontbold)?"normal":"bold"}},subtitle:{text:ia(a.subcaption),style:{fontFamily:b(a.subcaptionfontfamily,
a.captionfontfamily,z),color:b(a.subcaptionfontcolor,a.captionfontcolor,B).replace(/^#?([a-f0-9]+)/ig,"#$1"),fontSize:e(a.subcaptionfontsize,e(sa(a.captionfontsize-3,1),x))+"px",fontWeight:0===e(a.subcaptionfontbold)?"normal":"bold"}},orphanStyles:{defaultStyle:{style:G({},k.inCanvasStyle)}},tooltip:{enabled:0!==k.showTooltip,style:{fontFamily:v,fontSize:y,lineHeight:u,color:r,padding:e(a.tooltippadding,this.tooltippadding,3)+"px",backgroundColor:Z(b(q.backgroundColor,a.tooltipbgcolor,t.tooltipbgcolor),
b(a.tooltipbgalpha,"100")),borderColor:Z(b(q.borderColor,a.tooltipbordercolor,t.tooltipbordercolor),b(a.tooltipborderalpha,"100")),borderWidth:e(a.tooltipborderthickness,w)+"px",borderRadius:e(a.tooltipborderradius,l+1)+"px"},constrain:e(a.constraintooltip,1),shadow:e(a.showtooltipshadow,a.showshadow,1)?{enabled:!0,opacity:sa(e(a.tooltipbgalpha,100),e(a.tooltipborderalpha,100))/100}:!1},legend:{itemStyle:{fontFamily:b(a.legenditemfont,z),fontSize:e(a.legenditemfontsize,x)+"px",color:Y(b(a.legenditemfontcolor,
B)),fontWeight:e(a.legenditemfontbold)?"bold":"normal"},itemHiddenStyle:{fontFamily:z,fontSize:C,color:Y(b(a.legenditemhiddencolor,B))},itemHoverStyle:{color:Y(b(a.legenditemhoverfontcolor,a.legenditemfontcolor,B))},enabled:e(a.showlegend,1),title:{text:ia(a.legendcaption),style:{fontFamily:b(a.legendcaptionfont,z),fontSize:e(a.legendcaptionfontsize,x)+"px",color:Y(b(a.legendcaptionfontcolor,B)),fontWeight:e(a.legendcaptionfontbold,1)?"bold":"normal"},align:T[b(a.legendcaptionalignment)]},position:b(a.legendposition,
0===e(h.colorrange&&h.colorrange.gradient,0)?"right":"bottom"),backgroundColor:b(a.legendbgcolor,t.bgcolor),backgroundAlpha:b(a.legendbgalpha,"100"),borderColor:b(a.legendbordercolor,t.legendbordercolor),borderThickness:b(a.legendborderthickness,"1"),borderAlpha:b(a.legendborderalpha,"100"),shadow:e(a.legendshadow,1),allowDrag:e(a.legendallowdrag,0),scroll:{scrollBgColor:b(a.legendscrollbgcolor,a.scrollcolor,"AAAAAA"),scrollBtnColor:b(a.legendscrollbtncolor,"BBBBBB"),scrollBarColor:b(a.legendscrollbarcolor,
"CCCCCC")},reversed:e(a.reverselegend,0),interactive:e(a.interactivelegend,0),minColor:Q,lighting3d:n},markers:{dataLabels:{style:{fontFamily:b(a.markerfont,v),fontSize:e(a.markerfontsize,parseInt(y,10)),fontColor:b(a.markerfontcolor,r)}},showTooltip:e(a.showmarkertooltip,k.showTooltip),showLabels:e(a.showmarkerlabels,a.showlabels,1),showHoverEffect:e(a.showmarkerhovereffect,1),labelPadding:b(a.markerlabelpadding,"5"),labelWrapWidth:e(a.markerlabelwrapwidth,0),labelWrapHeight:e(a.markerlabelwrapheight,
0),fillColor:b(a.markerfillcolor,a.markerbgcolor,t.markerfillcolor),fillAlpha:b(a.markerfillalpha,t.markerfillalpha),fillAngle:b(a.markerfillangle,t.markerfillangle),fillRatio:b(a.markerfillratio,t.markerfillratio),fillPattern:b(a.markerfillpattern,t.markerbgpattern),hoverFillColor:a.markerfillhovercolor,hoverFillAlpha:a.markerfillhoveralpha,hoverFillRatio:a.markerfillhoverratio,hoverFillAngle:a.markerfillhoverangle,borderThickness:b(a.markerborderthickness,1),borderColor:b(a.markerbordercolor,t.markerbordercolor),
borderAlpha:e(a.markerborderalpha,t.markerborderalpha),hoverBorderThickness:a.markerborderhoverthickness,hoverBorderColor:a.markerborderhovercolor,hoverBorderAlpha:a.markerborderhoveralpha,radius:e(a.markerradius&&D.trimString(a.markerradius),7),shapeId:b(a.defaultmarkershape,"circle"),labelSepChar:b(a.labelsepchar,", "),tooltipSepChar:k.tooltipSepChar,autoScale:e(a.autoscalemarkers,0),tooltext:b(g&&g.tooltext,a.markertooltext),dataEnabled:k.useValuesForMarkers,valueToRadius:e(a.markerradiusfromvalue,
1),valueMarkerAlpha:b(a.valuemarkeralpha,"75"),hideNull:e(a.hidenullmarkers,0),nullRadius:e(a.nullmarkerradius,a.markerradius,7),adjustViewPort:e(a.adjustviewportformarkers,0),startAngle:e(a.markerstartangle,90),maxRadius:e(a.maxmarkerradius,0),minRadius:e(a.minmarkerradius,0),applyAll:e(a.applyallmarkers,0),shadow:e(a.showmarkershadow,a.showshadow,0)},connectors:{showHoverEffect:e(a.showconnectorhovereffect,1),thickness:e(a.connectorthickness,a.markerconnthickness,"2"),color:b(a.connectorcolor,a.markerconncolor,
t.markerbordercolor),alpha:b(a.connectoralpha,a.markerconnalpha,"100"),hoverthickness:e(a.connectorhoverthickness,a.connectorthickness,a.markerconnthickness,"2"),hovercolor:b(a.connectorhovercolor,a.connectorcolor,a.markerconncolor,t.markerbordercolor),hoveralpha:b(a.connectorhoveralpha,a.connectoralpha,a.markerconnalpha,"100"),dashed:e(a.connectordashed,a.markerconndashed,0),dashLen:e(a.connectordashlen,a.markerconndashlen,3),dashGap:e(a.connectordashgap,a.markerconndashgap,2),font:b(a.connectorfont,
a.markerconnfont,v),fontColor:b(a.connectorfontcolor,a.markerconnfontcolor,r),fontSize:e(a.connectorfontsize,a.markerconnfontsize,parseInt(y,10)),showLabels:e(a.showconnectorlabels,a.showmarkerlabels,a.showlabels,1),labelBgColor:b(a.connectorlabelbgcolor,a.markerconnlabelbgcolor,t.plotfillcolor),labelBorderColor:b(a.connectorlabelbordercolor,a.markerconnlabelbordercolor,t.markerbordercolor),shadow:e(a.showconnectorshadow,a.showmarkershadow,a.showshadow,0),showTooltip:e(a.showconnectortooltip,a.showmarkertooltip,
k.showTooltip),tooltext:b(g&&g.connectortooltext,a.connectortooltext),hideOpen:e(a.hideopenconnectors,1)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:v,fontSize:y,lineHeight:u,color:f.plotOptions.series.dataLabels.color=r}},fillColor:L,fillAlpha:F,fillRatio:K,fillAngle:O,borderColor:J,borderAlpha:b(a.entityborderalpha,a.borderalpha,this.borderAlpha,"100"),borderThickness:e(a.showentityborder,a.showborder,1)?e(a.entityborderthickness,a.borderthickness,1):0,scaleBorder:e(a.scaleentityborder,
a.scaleborder,0),hoverFillColor:b(a.entityfillhovercolor,a.hoverfillcolor,a.hovercolor,t.plothoverfillcolor),hoverFillAlpha:b(a.entityfillhoveralpha,a.hoverfillalpha,a.hoveralpha,t.plothoverfillalpha),hoverFillRatio:b(a.entityfillhoverratio,a.hoverfillratio,a.hoverratio,t.plothoverfillratio),hoverFillAngle:b(a.entityfillhoverangle,a.hoverfillangle,a.hoverangle,t.plothoverfillangle),hoverBorderThickness:b(a.entityborderhoverthickness,a.hoverborderthickness),hoverBorderColor:b(a.entityborderhovercolor,
t.plotbordercolor),hoverBorderAlpha:b(a.entityborderhoveralpha,t.plotborderalpha),nullEntityColor:Q,nullEntityAlpha:b(a.nullentityfillalpha,a.nullentityalpha,F),nullEntityRatio:b(a.nullentityfillratio,a.nullentityratio,K),nullEntityAngle:b(a.nullentityfillangle,a.nullentityangle,O),connectorColor:b(a.labelconnectorcolor,a.connectorcolor,r),connectorAlpha:b(a.labelconnectoralpha,a.connectoralpha,"100"),connectorThickness:e(a.labelconnectorthickness,a.borderthickness,1),showHoverEffect:e(a.showentityhovereffect,
a.usehovercolor,k.showHoverEffect),hoverOnNull:e(a.hoveronnull,a.entityhoveronnull,1),labelPadding:e(a.labelpadding,5),showLabels:e(a.showlabels,1),labelsOnTop:e(a.entitylabelsontop,1),includeNameInLabels:e(a.includenameinlabels,1),includeValueInLabels:e(a.includevalueinlabels,0),useSNameInTooltip:e(a.usesnameintooltip,0),useShortName:e(a.usesnameinlabels,1),labelSepChar:b(a.labelsepchar,", "),showTooltip:e(a.showentitytooltip,k.showTooltip),tooltipSepChar:k.tooltipSepChar,tooltext:a.entitytooltext,
hideNullEntities:e(a.hidenullentities,0),showHiddenEntityBorder:e(a.showhiddenentityborder,1),showNullEntityBorder:e(a.shownullentityborder,1),hiddenEntityColor:b(a.hiddenentitycolor,a.hiddenentityfillcolor,a.hiddenentityalpha||a.hiddenentityfillalpha?Q:"ffffff"),hiddenEntityAlpha:b(a.hiddenentityalpha,a.hiddenentityfillalpha,.001),shadow:e(a.showshadow,this.defaultPlotShadow,t.shadow)},entitydef:{useSNameAsId:e(a.usesnameasid,0)}});f.legend.title.style.lineHeight=ja(f.legend.title.style);f.legend.itemStyle.lineHeight=
ja(f.legend.itemStyle);f.legend.itemHiddenStyle.lineHeight=ja(f.legend.itemHiddenStyle);g=Ca(d,c,a.markermaxradius,a.markerminradius);f.markers.maxRadius=g.max;f.markers.minRadius=g.min;a.tooltipcolor&&(f.tooltip.style.color=ma(a.tooltipcolor));void 0!==b(a.clickurl)&&(m.link=a.clickurl,m.style.cursor="pointer",ka&&(m.style._cursor="hand"),f.plotOptions.series.point.events.click=function(){m.events.click.call({link:a.clickurl})});g=m.bgImageDisplayMode;k=ua(a.bgimagevalign,"").toLowerCase();l=ua(a.bgimagehalign,
"").toLowerCase();"tile"==g||"fill"==g||"fit"==g?("top"!=k&&"middle"!=k&&"bottom"!=k&&(k="middle"),"left"!=l&&"middle"!=l&&"right"!=l&&(l="middle")):("top"!=k&&"middle"!=k&&"bottom"!=k&&(k="top"),"left"!=l&&"middle"!=l&&"right"!=l&&(l="left"));m.bgImageVAlign=k;m.bgImageHAlign=l;this.parseStyles(f);ja(f.title.style);ja(f.subtitle.style);ja(f.tooltip.style);f.plotOptions.series.allowPointSelect=!0;this.parseExportOptions(f);this.preSeriesAddition&&this.preSeriesAddition(f,h,d,c);this.series&&this.series(h,
f,this.name,d,c);this.postSeriesAddition&&this.postSeriesAddition(f,h,d,c);this.spaceManager(f,h,d,c);fa.console&&fa.FC_DEV_ENVIRONMENT&&fa.console.log(f);return f},series:function(d,c){function h(d){for(J=d&&d.length||0;J--;)z=d[J],p=z.value,z.cleanValue=a.getCleanValue(p),z.formattedValue=null!==z.cleanValue?a.dataLabels(p):void 0,z.origValue=p,null!==z.cleanValue&&(r=ca(z.cleanValue,r),x=sa(z.cleanValue,x))}function f(a,d,f){for(J=a&&a.length||0;J--;){z=a[J];var h;a:{h=e(z.value);for(var g=void 0,
l=void 0,g=void 0,E=A&&A.length||0;E--;)if(g=A[E],l=Number(g.maxvalue),g=e(g.minvalue,c.colorRange.scaleMin),h>=g&&h<=l){h=E;break a}h=null}H=h;null!==H&&(C="gradient"===v.type?c.colorRange.getColorObj(z.value).code:t&&t[H]&&b(t[H].color,t[H].code),y[H]||(y[H]=[]),C&&(z.color=z.color?z.color:C,d&&(z.alpha=z.alpha?z.alpha:d),f&&(w||z.fillhoveralpha||(z.fillhoveralpha=z.alpha),k||z.fillhovercolor||(z.fillhovercolor=z.color)),y[H].push(z)))}}var a=this.numberFormatter,g=this.hcJSON.series,m=c.markers.valueMarkerAlpha,
k=c.markers.hasHoverColor,w=c.markers.hasHoverAlpha,l=this.dataObj,n=c[ra],q=l.colorrange,t=q&&q.color,v=c.legend,y={},q={legendClick:function(){var a;if(a=this.chart)!this.legend&&(this.legend=this.plot.legend),a.legendClick(this,!this.visible)},getEventArgs:function(){var a;if(a=this.chart)return!this.legend&&(this.legend=this.plot.legend),a.getEventArgs(this)},setVisible:function(a){var d=this.data,b=this.legendItem,c=this.visible;this.visible=a=void 0===a?!c:a;b&&v.colorizeItem&&v.colorizeItem(this,
a);for(c=d&&d.length;c--;)(b=d[c].mapItem)&&(a?b.show&&b.show():b.hide&&b.hide())}},r=Infinity,x=-Infinity,z,C,B,A,p,H,u,J;h(l.data||[]);n.useValuesForMarkers&&h(l.markers&&l.markers.items||[]);n._doNotShowLegend=!0;v.type=l.colorrange&&"1"===l.colorrange.gradient?"gradient":"point";Infinity===r&&(r=void 0);-Infinity===x&&(x=void 0);n.dataMin=r;n.dataMax=x;c.colorRange=new D.colorRange({colorRange:l.colorrange,dataMin:r,dataMax:x,defaultColor:v.minColor,numberFormatter:a});J=(A=c.colorRange.colorArr)&&
A.length||0;if(0<J){for(;J--;)B=A[J],!n._doNotShowLegend||""===B.label&&void 0===B.label||(n._doNotShowLegend=!1),g.push(G({type:this.defaultSeriesType,showInLegend:!0,data:[],plot:{},name:B.label,color:B.code,rangeMin:B.minvalue,rangeMax:B.maxvalue,visible:!0},q));f(l.data||[]);n.useValuesForMarkers&&f(l.markers&&l.markers.items||[],m,!0);g=g.reverse();for(u in y)g[u]&&(g[u].data=y[u])}else g.push({type:this.defaultSeriesType,data:[]});n._doNotShowLegend&&(this.hcJSON.legend.enabled=!1)},preliminaryScaling:function(d,
b){for(var h=b.markers&&b.markers.items||[],f=h&&h.length||0,a=Infinity,e=Infinity,g=-Infinity,k=-Infinity,l,m;f--;)m=h[f],l=Number(m.x),m=Number(m.y),a=ca(a,l),e=ca(e,m),g=sa(g,l),k=sa(k,m);return{x:a,y:e,x1:g,y1:k}},getScalingParameters:function(d,b,h,f){var a=d/b,e=h/(d*this.baseScaleFactor),g=f/(b*this.baseScaleFactor),k=0,l=0;e>g?(e=g,k+=(h-f*a)/2,d=200/(b*e)):(l+=(f-h/a)/2,d=200/(d*e));return{scaleFactor:e,strokeWidth:d,translateX:k,translateY:l}},calculateMarkerBounds:function(b,c,h,f,a){var e=
b.markers,g=b[ra];b=g.dataMin;for(var g=g.dataMax,k=e.minRadius,l=e.maxRadius,m=e.hideNull,n=e.nullRadius,e=e.valueToRadius,q=(c=c.markers&&c.markers.items||[],c.length)||0,t=Infinity,v=Infinity,y=-Infinity,r=-Infinity,x,z,A;q--;)z=c[q],null!==z.cleanValue?(e&&void 0===z.radius&&(z.radius=k+(l-k)*(z.cleanValue-b)/(g-b)),A=Number(z.radius),x=(Number(z.x)+f)*h,z=(Number(z.y)+a)*h,t=ca(t,x-A),v=ca(v,z-A),y=sa(y,x+A),r=sa(r,z+A)):m?z.__hideMarker=!0:void 0===z.radius&&(z.radius=n);return{x:t,y:v,x1:y,
y1:r}},spaceManager:function(b,c,h,f){var a=b.chart,e=b[ra],g=a.spacingLeft,k=a.spacingTop,l=this.baseWidth,m=this.baseHeight;h-=a.spacingRight+g;a=f-(a.spacingBottom+k);f=e._captionBlock=this.manageTitleSpace(b,c,h,a);var n=e._legendBlock=this.placeLegendBlock(b,c,h,a-f.height,f.isBottom?f.height:0);h-=n.width;var a=a-f.height-n.height,q=n=0;e.useValuesForMarkers?(e.adjustViewPortForMarkers?(e=this.preliminaryScaling(b,c),e.x1>l&&(l=e.x1),0>e.x&&(l+=-e.x,q=-e.x),e.y1>m&&(m=e.y1),0>e.y&&(m+=-e.y,
n=-e.y),e=this.getScalingParameters(l,m,h,a),e=this.calculateMarkerBounds(b,c,e.scaleFactor*this.baseScaleFactor,q,n),b=a,c=h,0>e.x&&(g+=-e.x,h+=e.x),0>e.y&&(k+=-e.y,a+=e.y),e.x1>c&&(h-=e.x1-c),e.y1>b&&(a-=e.y1-b)):(e=this.getScalingParameters(l,m,h,a),this.calculateMarkerBounds(b,c,e.scaleFactor*this.baseScaleFactor,q,n)),e=this.getScalingParameters(l,m,h,a),g+=q*e.scaleFactor*this.baseScaleFactor,k+=n*e.scaleFactor*this.baseScaleFactor):e=this.getScalingParameters(l,m,h,a);/bottom/i.test(f.position)||
(k+=f.height);this.scaleFactor=e.scaleFactor;this.strokeWidth=e.strokeWidth;this.translateX=e.translateX+g;this.translateY=e.translateY+k},placeGLegendBlockRight:D.placeGLegendBlockRight,placeGLegendBlockBottom:D.placeGLegendBlockBottom,placeLegendBlock:function(b,c,e,f,a){var g=b.legend,l=b[ra],k=g.position.toLowerCase(),m={position:k};if("0"===c.chart.showlegend||l._doNotShowLegend)return m.height=0,m.width=0,m;"bottom"===k?(m.height="gradient"===g.type?this.placeGLegendBlockBottom(b,c,e,f):this.placeLegendBlockBottom(b,
c,e,f),m.width=0,a&&(g.y=-a)):(e/=2,m.width="gradient"===g.type?this.placeGLegendBlockRight(b,c,e,f):this.placeLegendBlockRight(b,c,e,f),m.height=0);return m},manageTitleSpace:function(b,c,e,f){var a=this.hcJSON;b=a.title;c=a.chart;var a=a.subtitle,g=this.smartLabel,l=f/2,k=0,m=b.position.toLowerCase(),n=b.padding,q=!1,v=b.offsetX,t=b.offsetY,A=0,y={},r,x;if(""===b.text&&""===a.text)return{height:0,position:m};isNaN(v)&&isNaN(t)||(q=!0,v=isNaN(v)?0:v,t=isNaN(t)?0:t);r=b.text;if(""!==r){g.setStyle(b.style);
x=g.getOriSize(r);if(x.width>e||x.height>l)x=g.getSmartText(r,e,l),b.text=x.text,x.tooltext&&(b.originalText=x.tooltext);b.height=A=x.height;k+=A}l-=k;r=a.text;if(""!==r){g.setStyle(a.style);x=g.getOriSize(r);if(x.width>e||x.height>l)x=g.getSmartText(r,e,l),a.text=x.text,x.tooltext&&(a.originalText=x.tooltext);k+=a.height=x.height}k=k+n>l?l:k+n;m.match(/left/)?(a.align=b.align="start",a.x=b.x=c.marginLeft):m.match(/right/)?(a.align=b.align="end",a.x=b.x=e):(a.align=b.align="middle",a.x=b.x=e/2);/bottom/.test(m)?
(e=f-k+c.marginTop+n,b.y=e,a.y=e+A,q?(b.y+=t,a.y+=t,b.x+=v,a.x+=v):(c.marginBottom+=k,y.isBottom=!0)):q?(b.y+=t,a.y+=t,b.x+=v,a.x+=v):c.marginTop+=k;y.height=q?0:k;y.position=m;return y},getFirstId:function(){return this.firstEntity},getEntityPaths:function(b){var c={},e=this.entities,f;if(b){for(f in e)c[f]=e[f];return c}return e},redefineEntities:function(b,c){var e=this.entities,f={},a={},g=0,l,k,m,n,q,v,t,A;for(t=b.length;t--;)if(l=b[t],k=l.internalid,q=l.newid?l.newid:k,m=l.sname,l=l.lname,n=
e[k],k=D.trimString(k),q=D.trimString(q),n){f[q]=q={origId:k};a[k]=!0;for(v in n)q[v]=n[v];q.shortLabel=m?m:n.shortLabel;q.label=l?l:n.label}this.entities={};for(A in f)f[A].origId=A,this.entities[A.toLowerCase()]=f[A],g+=1;for(A in e)if(q=e[A],A=D.trimString(A),!a[A]){c.useSNameAsId?(this.entities[q.shortLabel.toLowerCase()]=n={},n.origId=q.shortLabel):(this.entities[A.toLowerCase()]=n={},n.origId=A);for(v in q)n[v]=q[v];g+=1}this.entityCount=g},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",
borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",
tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerfillcolor:"backgrounddarkcolor",markerfillalpha:"backgrounddarkalpha",markerfillangle:"backgrounddarkangle",markerfillratio:"backgrounddarkratio",plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",
plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.hcObj.logic.name},getEntityList:function(){var b=this.jsVars.hcObj,b=b.entities&&b.entities.items,c,e=[],f,a;for(f in b)a=b[f],c=a.eJSON,e.push({id:a.id,originalId:a.originalId||a.id,label:c.label,shortlabel:c.shortLabel,
value:a.value,formattedValue:a.formattedValue,toolText:a.toolText});return e},getDataAsCSV:function(){var b=this.jsVars,b=b.hcObj&&b.hcObj.entities&&b.hcObj.entities.items,c='"Id","Short Name","Long Name","Value","Formatted Value"',e,f,a,g;for(e in b)f=b[e],a=f.eJSON,g=f.value,c+='\r\n"'+f.id+'","'+a.shortLabel+'","'+a.label+'","'+(void 0===g?"":g)+'","'+f.formattedValue+'"';return c},getMapAttribute:function(){var b=this.jsVars.fcObj;V.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",
'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return b.getChartAttribute.apply(b,arguments)},exportMap:function(){var b=this.jsVars.fcObj;V.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return b.exportChart&&b.exportChart.apply(b,arguments)},addMarker:function(b){this.jsVars.hcObj.markers.addMarkerItem(b)||V.raiseWarning(this,"1309264086","run","MapsRenderer~addMarker()","Failed to add marker. Check the options and try again.")},
updateMarker:function(b,c){var e=this.jsVars.hcObj,f=e.markers,e=e.mapAnnotations,a;b&&(b=(b+"").toLowerCase(),f=f.items[b])&&(a=f.options,G(a,c),f=f.draw().markerShape,e.update(b,f))},removeMarker:function(b){var c=this.jsVars.hcObj.markers,e;b&&(b=(b+"").toLowerCase(),(e=c.items[b])&&e.destroy(),delete c.items[b])}}},O.linebase);O("renderer.maps",{drawGraph:function(){var b=this.paper,c=this.layers,e,f,a;if(!this.options.nativeMessage){c.dataset||(c.dataset=b.group("dataset").insertAfter(c.background),
c.tracker=b.group("hot").insertAfter(c.dataset));this.shadowLayer||(this.shadowLayer=c.shadow=b.group("shadow").insertBefore(c.dataset));this.strokeWidth=this.logic.strokeWidth;e=this.logic.scaleFactor;this.translateX=f=this.logic.translateX;this.translateY=a=this.logic.translateY;this.sFactor=e*this.logic.baseScaleFactor;this.transformStr=["t",f,",",a,"s",e,",",e,",0,0"].join("");this.options.tooltip&&!1!==this.options.tooltip.enabled&&b.tooltip(this.options.tooltip.style,this.options.tooltip.shadow,
this.options.tooltip.constrain);this.mapAnnotations=new D.Annotations;this.mapAnnotations.reset(null,{id:"geo",showbelow:0,autoscale:0,grpxshift:this.translateX?this.translateX:0,grpyshift:this.translateY?this.translateY:0,xscale:100*(this.sFactor?this.sFactor:1),yscale:100*(this.sFactor?this.sFactor:1),options:{useTracker:!0}});this.processEntityDefs();this.drawEntities();if(!ka||za)c.dataset.attr({transform:this.transformStr}),c.shadow.attr({transform:this.transformStr});this.drawMarkers()}},setScaleRange:function(b,
c){for(var e=this.options.series,f=e.length,a,g,l,k;f--;)if(l=e[f],g=(a=l.data)&&a.length)if(l.rangeMin>=b&&l.rangeMax<=c)l.setVisible(!0);else if(l.rangeMax<b||l.rangeMin>c)l.setVisible(!1);else for(;g--;)l=(k=a[g].mapItem)&&k.value,isNaN(l)||""===l||(l>=b&&l<=c?k.show():k.hide())},processEntityDefs:function(){var b=this.logic,c=this.options.series,e=c&&c.length;for(b.redefineEntities(b.dataObj.entitydef||[],this.options.entitydef);e--;)c[e].chart=this},drawEntities:function(){this.entities=new n(this.logic&&
this.logic.dataObj&&this.logic.dataObj.data,this,this.logic,this.layers.dataset)},drawMarkers:function(){var b=this.logic&&this.logic.dataObj&&this.logic.dataObj.markers||null;b&&(this.markers=new v(b,this,this.group));this.options.entities.labelsOnTop||this.entities.drawLabels()},checkComplete:function(){var b=this.logic,c=b.chartInstance;this.entities&&this.entities.isReady()&&(this.mapAnnotations.draw(this),b.hasRendered=!0,V.raiseEvent("internal.mapdrawingcomplete",{renderer:this},c))}},O["renderer.root"])},
[3,2,0,"release"]]);
