/*
 FusionCharts JavaScript Library - Gantt Chart
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.6.0
*/
FusionCharts.register("module",["private","modules.renderer.js-gantt",function(){var ga=this,F=ga.hcLib,Qa=ga.window,wa=/msie/i.test(Qa.navigator.userAgent)&&!Qa.opera,tb=F.chartAPI,Ra=F.chartAPI,gb=F.extend2,e=F.pluck,d=F.pluckNumber,qa=F.getFirstColor,La=F.graphics,U=La.convertColor,hb=La.getDarkColor,jc=La.parseColor,Ea=F.parseUnsafeString,Ga=F.getFirstValue,ac=F.getValidValue,ma=F.Raphael,kc=F.COMMASTRING,Ma=F.setLineHeight,Gb=F.getDashStyle,Hb=F.toRaphaelColor,Sa=F.each,lc=F.FC_CONFIG_STRING,
Na="rgba(192,192,192,"+(wa?.002:1E-6)+")",bc=La.mapSymbolName,wa=Math,Oa=wa.ceil,xa=wa.round,X=wa.max,Fa=wa.min,cc=wa.abs,Ta=parseInt,Ib=parseFloat,mc={pageX:0,pageY:0},V=F.plotEventHandler,ja,ea,ub=F.hasTouch=void 0!==Qa.document.documentElement.ontouchstart,nc=F.addEvent,oc=F.removeEvent,Ua=function(b){return void 0!==b&&null!==b},Va={left:"start",right:"end",center:"middle"},ib={left:0,right:1,center:.5,undefined:.5},vb={top:1,bottom:0,middle:.5,undefined:.5},Wa={left:5,right:-5,center:0,undefined:0},
Ha=function(b,a){this.min=b.min;this.max=d(b.visibleMax,b.max);this.pixelValueRatio=a/(this.max-this.min);this.startPixel=b.chart.marginLeft+b.chart.ganttStartX};Ha.prototype={getPixel:function(b){return this.startPixel+(b-this.min)*this.pixelValueRatio}};Ha.prototype.constructor=Ha;tb("gantt",{friendlyName:"Gantt Chart",rendererId:"gantt",standaloneInit:!0,defaultSeriesType:"gantt",canvasborderthickness:1,defaultPlotShadow:1,creditLabel:!1,fireGroupEvent:!0,defaultPaletteOptions:function(){var b=
arguments;return F.extend2(F.extend2(F.extend2(F.extend2({},b[0]),b[1]),b[2]),b[3])}(gb({},F.defaultGaugePaletteOptions),{paletteColors:["AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),
"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" ")],bgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],bgAngle:[270,270,270,270,270],bgRatio:["100","100","100","100","100"],bgAlpha:["100","100","100",
"100","100"],canvasBgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],canvasBgAngle:[0,0,0,0,0],canvasBgAlpha:["100","100","100","100","100"],canvasBgRatio:["","","","",""],canvasBorderColor:["545454","545454","415D6F","845001","68001B"],canvasBorderAlpha:[100,100,100,90,100],gridColor:["DDDDDD","D8DCC5","99C4CD","DEC49C","FEC1D0"],gridResizeBarColor:["999999","545454","415D6F","845001","D55979"],categoryBgColor:["F1F1F1","EEF0E6","F2F8F9","F7F0E6","FFF4F8"],dataTableBgColor:["F1F1F1","EEF0E6",
"F2F8F9","F7F0E6","FFF4F8"],toolTipBgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],toolTipBorderColor:["545454","545454","415D6F","845001","68001B"],baseFontColor:["555555","60634E","025B6A","A15E01","68001B"],borderColor:["767575","545454","415D6F","845001","68001B"],borderAlpha:[50,50,50,50,50],legendBgColor:["ffffff","ffffff","ffffff","ffffff","ffffff"],legendBorderColor:["666666","545454","415D6F","845001","D55979"],plotBorderColor:["999999","8A8A8A","6BA9B6","C1934D","FC819F"],plotFillColor:["EEEEEE",
"D8DCC5","BCD8DE","E9D8BE","FEDAE3"],scrollBarColor:["EEEEEE","D8DCC5","99C4CD","DEC49C","FEC1D0"]}),charttopmargin:10,chartbottommargin:20,series:function(){var b=this.dataObj,a=b.chart,J=(J=b.categories)||[],c=J.length,p=this.hcJSON,k=p.chart,t=p[lc],z=this.smartLabel,f=this.colorManager,g=p.categories={},w=[],n=this.inCanvasStyle,r=this.numberFormatter,D=Infinity,l=-Infinity,u=k.origW-k.marginLeft-k.marginRight,E=k.origH-k.marginTop-k.marginBottom,m=b.processes||{},h=m&&m.process,y=h&&h.length,
x=Ta(n.fontSize,10),R=b.datatable,ra=R&&R.datacolumn,H=ra&&ra.length,Y=b.connectors,M=Y&&Y.length,N=p.connectors=[],O=b.milestones&&b.milestones.milestone,C=O&&O.length,aa=p.milestone=[],I=b.tasks,ba=I&&I.task,L=ba&&ba.length,v=0,q=0,dc=d(a.forceganttwidthpercent,0),ca=0,V=0,ea=!1,ma={top:"top",bottom:"bottom"},B={top:"top",bottom:"bottom",undefined:"middle"},S={right:"right",left:"left"},da={right:"right",left:"left",undefined:"center"},G=p.dataTable={},jb=Infinity,kb=-Infinity,ja=p.processIDMap=
[],ga,wa,Oa=d(a.dateintooltip,1),La=b.legend&&b.legend.item,Ha=p.tasksMap||(p.tasksMap={}),Qa=0,Ra=0,wb,Ba,Jb,Kb,lb,xb,Sa,Lb,Mb,sa,ya,Ca,Va,ib,Wa,Sb,yb,tb,za,pa,mb,Q,Nb,Xa,Ya,Ob,Pb,Da,na,oa,Za,$a,ab,nb,bb,cb,Ia,Ja,ha,ub,Tb,ia,ka,fa,ob,pb,db,W,K,Ub,eb,zb,Ka,Ab,Vb,Qb,qb,Wb,Bb,Cb,Db,Eb,Fb,Rb,rb,vb,ec,fc,gc,Pa,T,hc,ua,P,Aa,ta,sb,la,Xb,Yb,Zb,$b,va,fb,ic,A,Z;if(y){p.tasks=[];delete p.yAxis;delete p.xAxis;k.backgroundColor=U(e(a.bgcolor,"FFFFFF"),e(a.bgalpha,f.getColor("bgAlpha")));d(a.showborder,0)||(k.borderWidth=
0);k.plotBorderColor=U(e(a.canvasbordercolor,f.getColor("canvasBorderColor")),0===d(a.showcanvasborder,1)?0:e(a.canvasborderalpha,100));k.backgroundColor={FCcolor:{color:e(a.bgcolor,"FFFFFF"),alpha:e(a.bgalpha,f.getColor("bgAlpha")),angle:e(a.bgangle,f.getColor("bgAngle")),ratio:e(a.bgratio,f.getColor("bgRatio"))}};k.plotBackgroundColor={FCcolor:{color:e(a.canvasbgcolor,f.getColor("canvasBgColor")),alpha:e(a.canvasbgalpha,f.getColor("canvasBgAlpha")),angle:e(a.canvasbgangle,f.getColor("canvasBgAngle")),
ratio:e(a.canvasbgratio,f.getColor("canvasBgRatio"))}};k.plotBorderWidth=d(a.canvasborderthickness,1);k.outputDateFormat=e(a.outputdateformat,k.dateFormat);k.extendCategoryBg=d(a.extendcategorybg,0);k.ganttLineColor=U(e(a.ganttlinecolor,f.getColor("gridColor")),d(a.ganttlinealpha,100));k.ganttLineThickness=d(a.ganttlinethickness,1);k.ganttLineDashStyle=d(a.ganttlinedashed,0)?Gb(d(a.ganttlinedashlen,1),a.ganttlinedashgap,k.ganttLineThickness):void 0;k.gridBorderColor=U(e(a.gridbordercolor,f.getColor("gridColor")),
d(a.gridborderalpha,100));k.gridBorderThickness=d(a.gridborderthickness,1);k.gridBorderDashStyle=d(a.gridborderdashed,0)?Gb(d(a.gridborderdashlen,1),a.gridborderdashgap,k.gridborderThickness):void 0;k.showSlackAsFill=d(a.showslackasfill,1);k.slackFillColor=qa(e(a.slackfillcolor,"FF5E5E"));k.gridResizeBarColor=U(e(a.gridresizebarcolor,f.getColor("gridResizeBarColor")),d(a.gridresizebaralpha,100));k.gridResizeBarThickness=d(a.gridresizebarthickness,1);k.taskBarRoundRadius=d(a.taskbarroundradius,0);
k.taskBarFillMix=a.taskbarfillmix;k.taskBarFillRatio=a.taskbarfillratio;void 0===k.taskBarFillMix&&(k.taskBarFillMix="{light-10},{dark-20},{light-50},{light-85}");void 0===k.taskBarFillRatio&&(k.taskBarFillRatio="0,8,84,8");k.connectorExtension=d(a.connectorextension,10);k.clickURL=e(a.clickurl,"");k.annRenderDelay=a.annrenderdelay;k.taskDatePadding=d(a.taskdatepadding,3);k.taskLabelPadding=d(a.tasklabelspadding,2);k.ganttStartX=d(a.ganttwidthpercent,65);100<k.ganttStartX&&(k.ganttStartX=100);Ca=
k.ganttStartX=.01*(100-k.ganttStartX)*u;k.gridWidth=u-k.ganttStartX;ic=d(a.showfulldatatable,1);db=m.width;db=d(k.ganttStartX*(/\%/g.test(db)&&.01*Ib(db,10))||db);Ca-=d(db,0);ga=xa(db);V+=1;for(A=0;A<H;A+=1)Lb=ra[A].width,Mb=d(k.ganttStartX*(/\%/g.test(Lb)&&.01*Ib(Lb,10))||Lb),Ca-=d(Mb,0),Mb=ra[A].width=xa(Mb),V+=1;0<=Ca?Ca/=V:(ea=!0,Ca=k.ganttStartX/V);if(dc||!ic)for((isNaN(ga)||ea)&&(ga=Ca),A=0;A<H;A+=1)(isNaN(ra[A].width)||ea)&&(ra[A].width=Ca);for(A=0;A<c;A+=1){ka=J[A];D=Infinity;l=-Infinity;
ob=e(ka.bgcolor,f.getColor("categoryBgColor"));pb=d(ka.bgalpha,100);Za=e(ka.font,n.fontFamily);$a=d(ka.fontsize,x+1);ab=e(ka.fontcolor,n.color);nb=d(ka.isbold,1);bb=d(ka.isitalic,0);cb=d(ka.isunderline,0);d(ka.verticalpadding,3);Ia=e(ka.align,"center").toLowerCase();Ja=e(ka.valign,"middle").toLowerCase();ub=(Tb=ka.category)&&Tb.length;Pa=0;la={};for(Z=0;Z<ub;Z+=1)ia=Tb[Z],na=r.getDateValue(ia.start).ms,oa=r.getDateValue(ia.end).ms,isNaN(na)&&(na=void 0),na>l&&(l=na),na<=D&&(D=na),isNaN(oa)&&(oa=void 0),
oa>l&&(l=oa),oa<=D&&(D=oa),ha=Ea(e(ia.label,ia.name)),T={color:qa(e(ia.fontcolor,ab)),fontFamily:e(ia.font,Za),fontSize:d(ia.fontsize,$a)+"px",fontWeight:d(ia.isbold,nb)&&"bold"||"normal",fontStyle:d(ia.isitalic,bb)&&"italic"||"normal",textDecoration:d(ia.isunderline,cb)&&"underline"||"none"},Ma(T),z.setStyle(T),sa=z.getOriSize(ha),Pa=X(Pa,sa.height),P="FCCAT_"+A+"_"+Z,Jb=e(ia.hoverbandcolor,ka.hoverbandcolor,a.categoryhoverbandcolor,a.hoverbandcolor,f.getColor("gridColor")),Kb=d(ia.hoverbandalpha,
ka.hoverbandalpha,a.categoryhoverbandalpha,a.hoverbandalpha,30),lb=d(ia.showhoverband,ka.showhoverband,a.showcategoryhoverband,a.showhoverband,a.showhovereffect,1),g[P]={text:ha,style:T,start:na,end:oa,index:Z,isLast:A===c-1,bgColor:U(e(ia.bgcolor,ob),d(ia.bgalpha,pb)),dimension:la,link:ia.link,align:da[[e(ia.align,Ia).toLowerCase()]],vAlign:B[ma[e(ia.valign,Ja).toLowerCase()]],hoverColor:U(Jb,Kb),useHover:lb,usePlotHover:d(ia.showganttpanehoverband,ka.showganttpanehoverband,a.showganttpaneverticalhoverband,
lb)},g[Aa]&&(g[Aa].nextCol=g[P],g[P].prevCol=g[Aa]),Aa=P;if(zb=g["FCCAT_"+A+"_0"])g[P].first=zb,zb.last=g[P],g[eb]&&(g[eb].nextRow=zb,zb.prevRow=g[eb]);eb=P;la.h=Pa+5+2*d(ka.verticalpadding,3);la.y=q;la.min=D;la.max=l;la.numCat=Z;q+=la.h;kb=X(kb,l);jb=Fa(jb,D)}g.min=jb;g.max=kb;if(y){Pa=ya=0;fb="right"===e(m.positioningrid,"left").toLowerCase();T={color:qa(e(m.headerfontcolor,n.color)),fontFamily:e(m.headerfont,n.fontFamily),fontSize:d(m.headerfontsize,x+3)+"px",fontWeight:d(m.headerisbold,1)&&"bold"||
"normal",fontStyle:d(m.headerisitalic,0)&&"italic"||"normal",textDecoration:d(m.headerisunderline,0)&&"underline"||"none"};Ma(T);ha=Ea(m.headertext);z.setStyle(T);sa=z.getOriSize(ha);ya=X(ya,sa.width);Ia=da[S[e(m.headeralign,"center").toLowerCase()]];Ja=B[ma[e(m.headervalign,"middle").toLowerCase()]];la={};P=ta=eb="processHeader";G.processHeader={text:ha,style:T,align:Ia,vAlign:Ja,isHeader:!0,link:e(m.headerlink),dimension:{x:0,w:0,h:X(sa.height,q)},bgColor:U(e(m.headerbgcolor,f.getColor("dataTableBgColor")),
d(m.headerbgalpha,100)),key:P,isLast:fb,drawResizer:!fb&&H,prevCol:null,nextCol:null,prevRow:null,nextRow:null};ob=e(m.bgcolor,f.getColor("dataTableBgColor"));pb=d(m.bgalpha,100);Za=e(m.font,n.fontFamily);$a=d(m.fontsize,x);ab=e(m.fontcolor,n.color);nb=d(m.isbold,0);bb=d(m.isitalic,0);cb=d(m.isunderline,0);Ia=e(m.align,"center").toLowerCase();Ja=e(m.valign,"middle").toLowerCase();for(A=0;A<y;A+=1)fa=h[A],Jb=e(fa.hoverbandcolor,m.hoverbandcolor,a.processhoverbandcolor,a.hoverbandcolor,f.getColor("gridColor")),
Kb=d(fa.hoverbandalpha,m.hoverbandalpha,a.processhoverbandalpha,a.hoverbandalpha,30),lb=d(fa.showhoverband,m.showhoverband,a.showprocesshoverband,a.showhoverband,a.showhovereffect,1),T={color:qa(e(fa.fontcolor,ab)),fontSize:d(fa.fontsize,$a)+"px",fontFamily:e(fa.font,Za),fontWeight:d(fa.isbold,nb)&&"bold"||"normal",fontStyle:d(fa.isitalic,bb)&&"italic"||"normal",textDecoration:d(fa.isunderline,cb)&&"underline"||"none"},Ma(T),ha=Ea(e(fa.label,fa.name)),z.setStyle(T),sa=z.getOriSize(ha),Pa=X(Pa,sa.height),
ya=X(ya,sa.width),Aa=P,P=e(fa.id,"__FCDPID__"+A).toUpperCase(),G[P]&&(P="__FCDPID__"+A),ja[A]=P,Ua(wb=d(fa.height,a.rowheight))&&(wb=cc(wb),Qa+=wb||0,Ra+=1),G[P]={text:sa.text,style:T,link:fa.link,id:P,processHeight:wb,labelHeight:sa.height,align:da[[e(fa.align,Ia).toLowerCase()]],vAlign:B[ma[e(fa.valign,Ja).toLowerCase()]],bgColor:U(e(fa.bgcolor,ob),d(fa.bgalpha,pb)),prevCol:G[Aa],dimension:{},hoverColor:U(Jb,Kb),useHover:lb,usePlotHover:d(fa.showganttpanehoverband,m.showganttpanehoverband,a.showganttpanehorizontalhoverband,
lb),isLast:fb,nextCol:null,prevRow:null,nextRow:null},G[Aa]&&(G[Aa].nextCol=G[P]);G[P].first=G[ta];G[ta].last=G[P];G[ta].processCount=y;G[ta].countDefinedHeight=Ra;G[ta].totalHeight=Qa;wa=G[ta].maxProcessHeight=Pa+8;isNaN(ga)&&(ga=ya+10);ca+=ga;la.x=0;G[ta].dimension.w=la.w=ga;la.h=wa=X((E-G[ta].dimension.h)/y,wa)}fb&&(ca=0);if(H)for(p.datacolumns=[],A=0;A<H;A+=1){W=ra[A];ya=0;ob=qa(e(W.bgcolor,R.bgcolor,f.getColor("dataTableBgColor")));pb=d(W.bgalpha,R.bgalpha,100);Za=e(W.font,R.font,n.fontFamily);
ab=qa(e(W.fontcolor,R.fontcolor,n.color));$a=d(W.fontsize,R.fontsize,x);nb=d(W.isbold,R.isbold,0);bb=d(W.isitalic,R.isitalic,0);cb=d(W.isunderline,R.isunderline,0);Ia=da[S[e(W.align,R.align,"center").toLowerCase()]];Ja=B[ma[e(W.valign,R.valign,"middle").toLowerCase()]];T={color:qa(e(W.headerfontcolor,R.headerfontcolor,ab)),fontFamily:e(W.headerfont,R.headerfont,Za),fontSize:d(W.headerfontsize,R.headerfontsize,$a+3)+"px",fontWeight:d(W.headerisbold,R.headerisbold,1)&&"bold"||"normal",fontStyle:d(W.headerisitalic,
R.headerisitalic,bb)&&"italic"||"normal",textDecoration:d(W.headerisunderline,R.headerisunderline,cb)&&"underline"||"none"};Ma(T);ha=Ea(W.headertext);z.setStyle(T);sa=z.getOriSize(ha);ya=X(ya,sa.width);P=ta="_FCDtHeader_"+A;mb=G[P]={text:ha,style:T,align:da[S[e(W.headeralign,R.headeralign,Ia).toLowerCase()]],vAlign:B[ma[e(W.headervalign,R.headervalign,Ja).toLowerCase()]],link:e(W.headerlink),drawResizer:fb||A<H-1,dimension:{x:0+ca,w:W.width,h:G.processHeader&&G.processHeader.dimension.h},isHeader:!0,
key:P,bgColor:U(e(W.headerbgcolor,R.headerbgcolor,f.getColor("dataTableBgColor")),d(W.headerbgalpha,R.headerbgalpha,100))};mb.data=[];hc=W.text||[];sb=G.processHeader;Ka=G[eb];Ka.nextRow=G[P];G[P].prevRow=Ka;sb=sb.nextCol;Ka=Ka.nextCol;la={};eb=ta;for(Z=0;sb;sb=sb.nextCol,Ka=Ka.nextCol,Z+=1)Aa=P,P="_FCDt_"+A+"_"+Z,(ua=hc[Z])?(T={fontFamily:e(ua.font,Za),color:qa(e(ua.fontcolor,ab)),fontSize:d(ua.fontsize,$a)+"px",fontWeight:d(ua.isbold,nb)&&"bold"||"normal",fontStyle:d(ua.isitalic,bb)&&"italic"||
"normal",textDecoration:d(ua.isunderline,cb)&&"underline"||"none"},Ma(T),z.setStyle(T),ha=Ea(ua.label),sa=z.getOriSize(ha),ya=X(ya,sa.width),G[P]={text:ha,style:T,link:e(ua.link,""),bgColor:U(e(ua.bgcolor,ob),d(ua.bgalpha,pb)),align:da[S[e(ua.align,Ia).toLowerCase()]],vAlign:B[ma[e(ua.valign,Ja).toLowerCase()]],prevCol:G[Aa],dimension:la,nextCol:null,nextRow:null,prevRow:null}):G[P]={prevCol:G[Aa],dimension:la,isNaN:!0,nextCol:null,nextRow:null,prevRow:null},G[Aa].nextCol=G[P],G[P].prevRow=Ka,Ka.nextRow=
G[P],G[P].hoverColor=G[ja[Z]].hoverColor,G[P].useHover=G[ja[Z]].useHover,G[P].usePlotHover=G[ja[Z]].usePlotHover;G[P].first=G[ta];G[ta].last=G[P];isNaN(W.width)?mb.width=ya+10:mb.width=W.width;la.x=0+ca;ca+=G[ta].dimension.w=la.w=mb.width;la.h=wa;p.datacolumns.push(mb)}fb&&(fa=G.processHeader,fa.dimension.x=fa.nextCol.dimension.x=ca,ca+=ga);dc||(k.ganttStartX=Fa(k.ganttStartX,ca));k.totalGridWidth=ca;Yb=b.trendlines||{};p.trendlines=[];for(A=0;A<Yb.length;A+=1)for(C=(Zb=Yb[A].line)&&Zb.length,Z=0;Z<
C;Z+=1)va=Zb[Z],$b=d(va.istrendzone,0),Da=e(va.color,f.getColor("legendBorderColor")),T=gb({},t.trendStyle),T.color=U(Da),Ma(T),p.trendlines.push({start:r.getDateValue(va.start).ms,end:r.getDateValue(va.end).ms,displayValue:Ea(e(va.displayvalue,va.start)),color:U(Da,d(va.alpha,$b?40:99)),style:T,isTrendZone:$b,dashedStyle:d(va.dashed,0)?Gb(d(va.dashlen,3),d(va.dashgap,3),d(va.thickness,1)):void 0,thickness:d(va.thickness,1)});if(L){D=Infinity;l=-Infinity;d(a.taskbarroundradius,0);Ya=a.taskbarfillmix;
Ob=a.taskbarfillratio;void 0===Ya&&(Ya="{light-10},{dark-20},{light-50},{light-85}");void 0===Ob&&(Ob="0,8,84,8");k.shadow=d(a.showshadow,1);Sa=d(a.showslackasfill,1);for(A=0;A<L;A+=1)K=ba[A],Ub=v%y,na=r.getDateValue(K.start).ms,oa=r.getDateValue(K.end).ms,P=e(G[Ga(K.processid,"").toUpperCase()],G["__FCDPID__"+Ub],G[ja[Ub]]).id.toUpperCase(),Ab=d(K.alpha,I.alpha,100),Da=e(K.color,I.color,f.getColor("plotFillColor")),Qb=d(K.borderalpha,I.borderalpha,100),Vb=e(K.bordercolor,I.bordercolor,f.getColor("plotBorderColor")),
isNaN(na)&&(na=void 0),na>l&&(l=na),na<=D&&(D=na),isNaN(oa)&&(oa=void 0),oa>l&&(l=oa),oa<=D&&(D=oa),T={color:qa(e(K.fontcolor,I.fontcolor,n.color)),fontSize:d(K.fontsize,I.fontsize,x)+"px",fontFamily:e(K.font,I.font,n.fontFamily)},Ma(T),v+=1,qb=f.parseColorMix(Da,Ya),Wb=f.parseAlphaList(Ab.toString(),qb.length),Bb=f.parseRatioList(Ob,qb.length),Cb=d(K.angle,I.angle,270),Rb=f.parseColorMix(e(K.slackfillcolor,I.slackfillcolor,a.slackfillcolor,"FF5E5E"),Ya),rb=Fa(d(K.percentcomplete,-1),100),ha=Ga(e(K.label,
K.name),""),Fb="",d(K.showlabel,K.showname,I.showlabels,I.showname,a.showtasklabels,a.showtasknames,0)&&(Fb=ha),d(K.showpercentlabel,I.showpercentlabel,a.showpercentlabel,0)&&-1!==rb&&(Fb+=" "+rb+"%"),vb={FCcolor:{color:qb.join(),alpha:Wb,ratio:Bb,angle:Cb}},Rb=Sa?{FCcolor:{color:Rb.join(),alpha:Wb,ratio:Bb,angle:Cb}}:Na,ec={FCcolor:{color:f.parseColorMix(e(K.hoverfillcolor,I.hoverfillcolor,a.taskhoverfillcolor,hb(Da,80)),Ya).join(),alpha:f.parseAlphaList(e(K.hoverfillalpha,I.hoverfillalpha,a.taskhoverfillalpha,
Ab).toString(),qb.length),ratio:Bb,angle:Cb}},fc=U(e(K.hoverbordercolor,I.hoverbordercolor,a.taskhoverbordercolor,hb(Vb,80)),e(K.hoverborderalpha,I.hoverborderalpha,a.taskhoverborderalpha,Qb)),gc=Sa?{FCcolor:{color:f.parseColorMix(hb(e(K.slackhoverfillcolor,I.slackhoverfillcolor,a.slackhoverfillcolor,a.slackfillcolor,"FF5E5E"),80),Ya).join(),alpha:f.parseAlphaList(e(K.slackhoverfillalpha,I.slackhoverfillalpha,a.slackhoverfillalpha,Ab).toString(),qb.length),ratio:Bb,angle:Cb}}:Na,Db=r.getFormattedDate(na),
Eb=r.getFormattedDate(oa),Ba=ac(Ea(e(K.tooltext,K.hovertext,I.plottooltext,t.tooltext))),Ba=void 0!==Ba?F.parseTooltext(Ba,[3,28,29,30,31],{end:Eb,start:Db,label:ha,percentComplete:-1!==rb?r.percentValue(rb):"",processName:G[P]&&G[P].text},K):(""!==ha?ha+(Oa?", ":""):"")+(Oa?Db+" - "+Eb:""),Xa=Ga(K.id,"").toUpperCase(),Ha[Ga(Xa,A)]={dataObj:{processId:P,label:Fb,labelAlign:da[[e(K.labelalign,a.tasklabelsalign,"center").toLowerCase()]],link:K.link,start:na,end:oa,id:Ga(K.id,"").toUpperCase(),showAsGroup:d(K.showasgroup,
0),animation:d(K.animation,a.animation,a.defaultanimation,1),style:T,percentComplete:rb,color:Hb(vb),slackColor:Hb(Rb),hoverFillColor:Hb(ec),hoverBorderColor:fc,slackHoverColor:Hb(gc),showHoverEffect:d(K.showhovereffect,I.showhovereffect,a.showtaskhovereffect,a.showhovereffect,1),shadow:{opacity:X(Ab,Qb)/100,inverted:!0},borderColor:U(Vb,Qb),borderThickness:d(K.showborder,I.showborder,1)?d(K.borderthickness,I.borderthickness,1):0,height:e(K.height,"35%"),topPadding:e(K.toppadding,"35%"),showPercentLabel:d(K.showpercentlabel,
I.showpercentlabel,a.showpercentlabel,0),startDate:d(K.showstartdate,I.showstartdate,a.showtaskstartdate)?Db:void 0,endDate:d(K.showenddate,I.showenddate,a.showtaskenddate)?Eb:void 0,toolText:Ba,_start:K.start,_end:K.end,_formatSDate:Db,_formatEDate:Eb,_label:ha}},w.push(Ha[Ga(Xa,A)].dataObj);kb=X(kb,l);jb=Fa(jb,D)}p.series.push({showInLegend:!1,data:w});C=O&&O.length;for(A=0;A<C;A+=1)Q=O[A],Xa=Ga(Q.taskid,"").toUpperCase(),Pb=e(Q.shape,"polygon").toLowerCase(),Nb=d(Q.numsides,5),Xb=0,"star"===Pb?
Xb=.4:(Pb=bc(Nb),Pb=bc(Nb).split("-")[0]),Da=e(Q.color,f.getColor("legendBorderColor")),Ba=ac(Ea(e(Q.tooltext,Q.hovertext,a.milestonetooltext))),void 0!==Ba&&Ha[Xa]?(K=Ha[Xa].dataObj,Ba=F.parseTooltext(Ba,[28,32,33,34,35,36],{date:r.getFormattedDate(Q.date),taskStartDate:K._formatSDate,taskEndDate:K._formatEDate,taskLabel:K._label,taskPercentComplete:-1!==K.percentComplete?r.percentValue(K.percentComplete):"",processName:G[K.processId]&&G[K.processId].text},Q)):Ba=r.getFormattedDate(Q.date),T={color:qa(e(Q.fontcolor,
a.milestonefontcolor,n.color)),fontSize:d(Q.fontsize,a.milestonefontsize,x)+"px",fontFamily:e(Q.font,a.milestonefont,n.fontFamily),fontWeight:d(Q.fontbold,a.milestonefontbold,0)&&"bold"||"normal",fontStyle:d(Q.fontitalic,a.milestonefontitalic,0)&&"italic"||"normal"},Ma(T),aa.push({numSides:Nb,startAngle:d(Q.startangle,90),radius:Q.radius,origDate:Q.date,date:r.getDateValue(Q.date),fillColor:qa(Da),fillAlpha:.01*d(Q.fillalpha,Q.alpha,100),borderColor:qa(e(Q.bordercolor,Da)),borderAlpha:.01*d(Q.borderalpha,
Q.alpha,100),displayValue:Ea(Q.label),style:T,hoverFillColor:qa(e(Q.hoverfillcolor,a.milestonehoverfillcolor,hb(Da,80))),hoverFillAlpha:.01*d(Q.hoverfillalpha,a.milestonehoverfillalpha,Q.fillalpha,Q.alpha,100),hoverBorderColor:qa(e(Q.hoverbordercolor,a.milestonehoverbordercolor,hb(e(Q.bordercolor,Da),80))),hoverBorderAlpha:.01*d(Q.hoverborderalpha,a.milestonehoverborderalpha,Q.borderalpha,Q.alpha,100),showHoverEffect:d(Q.showhovereffect,a.showmilestonehovereffect,a.showhovereffect,1),depth:Xb,taskId:Xa,
borderThickness:d(Q.borderthickness,1),link:Q.link,toolText:Ba});for(A=0;A<M;A+=1)if(ib=(Va=(za=Y[A])&&za.connector)&&Va.length)for(Z=0;Z<ib;Z+=1)pa=Va[Z],Wa=e(pa.color,za.color,f.getColor("plotBorderColor")),Sb=d(pa.alpha,za.alpha,100),yb=d(pa.thickness,za.thickness,1),tb=d(pa.isdashed,za.isdashed,1),N.push({fromTaskId:Ga(pa.fromtaskid,"").toUpperCase(),toTaskId:Ga(pa.totaskid,"").toUpperCase(),fromTaskConnectStart:d(pa.fromtaskconnectstart,0),toTaskConnectStart:d(pa.totaskconnectstart,1),color:U(Wa),
alpha:.01*Sb,link:pa.link,showHoverEffect:d(pa.showhovereffect,za.showhovereffect,a.showconnectorhovereffect,a.showhovereffect,1),hoverColor:U(e(pa.hovercolor,za.hovercolor,a.connectorhovercolor,hb(Wa,80)),d(pa.hoveralpha,za.hoveralpha,a.connectorhoveralpha,Sb)),hoverThickness:d(pa.hoverthickness,za.hoverthickness,a.connectorhoverthickness,yb),thickness:yb,dashedStyle:tb?Gb(d(pa.dashlen,za.dashlen,5),d(pa.dashgap,za.dashgap,yb),yb):void 0});p.legend.enabled=Boolean(d(a.showlegend,1));p.legend.interactiveLegend=
!1;p.legend.itemStyle.cursor="default";p.legend.itemHoverStyle={cursor:"inherit"};C=La&&La.length;for(A=0;A<C;A+=1)xb=La[A],Ua(xb.label)&&""!==xb.label&&p.series.push({name:Ea(xb.label),showInLegend:!0,type:!1,color:jc(e(xb.color,f.getPlotColor()))});p.max=kb;p.min=jb;p.chart.hasScroll=!0;return p}},spaceManager:function(b,a,J,c){this.titleSpaceManager(b,a,J,.3*c);var p=this.numberFormatter,k=b.chart,t=a.chart,z=b.dataTable,f=b.categories,g=b.scrollOptions={},w=z.__scrollOptions={},n=z.processHeader;
c=c-k.marginTop-k.marginBottom;J=J-k.marginLeft-k.marginRight;var r=k.totalGridWidth,D=b.verticalScroll={enabled:d(t.useverticalscrolling,1)},l=d(t.ganttpaneduration,-1),u=e(t.ganttpanedurationunit,"s").toLowerCase(),E=p.getDateValue(t.scrolltodate).ms,m=n&&n.maxProcessHeight,h,y,p=0;if(n){h=n.processCount-n.countDefinedHeight;b.legend.enabled&&(c-=this.placeLegendBlockBottom(b,a,J,c/2));c-=n.dimension.h;g.padding=d(t.scrollpadding,b.chart.plotBorderWidth/2);g.height=d(t.scrollheight,16);g.showButtons=
!!d(t.scrollshowbuttons,1);g.buttonPadding=d(t.scrollbtnpadding,0);g.flatScrollBars=d(t.flatscrollbars,0);g.color=qa(e(t.scrollcolor,this.colorManager.getColor("altHGridColor")));a=g.height+g.padding;r>k.ganttStartX&&(w.enabled=!0,w.startPercent=Boolean(d(t.scrolltoend,0)));J-=k.ganttStartX;f.scroll={};g=new Date(f&&f.min);if(-1!==l){switch(u){case "y":g.setYear(g.getFullYear()+l);break;case "m":g.setMonth(g.getMonth()+l);break;case "d":g.setDate(g.getDate()+l);break;case "h":g.setHours(g.getHours()+
l);break;case "mn":g.setMinutes(g.getMinutes()+l);break;default:g.setSeconds(g.getSeconds()+l)}g=g.getTime();g>b.min&&g<b.max&&(b.visibleMax=g,f.scroll.enabled=!0)}if(w.enabled||f.scroll.enabled)c-=a;w=c-n.totalHeight;g=w/(h?h:n.processCount);!d(t.forcerowheight,0)&&!h&&n.totalHeight<c&&(g=c/n.processCount,w=c,y=!0);m>g&&(m=3>m-g?g:w/xa(w/m));n.maxProcessHeight=m;D.enabled&&g<m&&h||0>g?(w=m,D.startPercent=Boolean(d(t.scrolltoend,0)),J-=a):(D.enabled=!1,w=g);f.scroll.startPercent=d(t.scrolltoend,0);
if(Infinity===b.min||-Infinity===b.max||b.min===b.max)b.min=f.min=0,b.max=f.max=1;if(Infinity===f.min||-Infinity===f.max)f.min=b.min,f.max=b.max;f.axis=new Ha(b,J);f.startX=f.axis.getPixel(Fa(f.min,b.min));f.endX=f.axis.getPixel(X(f.max,b.max));f.visibleW=J;E&&E>f.min&&E<f.max&&(f.scroll.startPercent=Fa((f.axis.getPixel(E)-f.startX)/(f.endX-f.startX-f.visibleW),1));for(n=n.nextCol;n;){p+=n.dimension.h=y?w:n.processHeight||w;if(b=n.nextRow)for(;b;)b.dimension.h=n.dimension.h,b=b.nextRow;n=n.nextCol}z.processHeader.totalPH=
p;k.processHeight=c+z.processHeader.dimension.h}}},tb.gaugebase);Ra("renderer.gantt",{drawProcess:function(b){var a=this,d=a.options,c=d.chart,p=a.paper,k=a.logic,t=k.smartLabel,z=a.canvasTop,f=a.canvasLeft,g=a.layers,w=g.gridLayer,n=g.gridHeaderLayer,r=c.gridBorderThickness,D=.5*r,l=c.gridBorderColor,u=c.gridBorderDashStyle,E=0,m=0,h=[],y=z,x=b.dimension.w||16,R=b.dimension.x||0,ra=d.dataTable.processHeader,H=ra.nextCol.dimension.h,Y=ra.totalPH,k=U(e(k.dataObj.chart.rolloverbandcolor,"#FF0000"),
e(k.dataObj.chart.rolloverbandalpha,30)),M=ra.items||(ra.items={}),d=d.categories||{},N,O,C,aa,I,ba,L,v,q,F,ca;M.hoverEle||(M.hoverEle=p.rect(d.startX,0,d.endX,H,0,g.dataset).attr({fill:k,visibility:"hidden","stroke-width":0}));q=function(b){V.call(this,a,b,"ProcessClick")};F=function(b){ja=clearTimeout(ja);if(!ea||ea.removed)ea=null;ea&&a.gridOutHandler.call(ea);a.gridHoverHandler.call(this);V.call(this,a,b,"ProcessRollOver")};for(ca=function(b){ea=this;ja=clearTimeout(ja);ja=setTimeout(function(){a.gridOutHandler.call(ea)},
500);V.call(ea,a,b,"ProcessRollOut")};b;)v=b.dimension,L=f+R,C=b.text,C=b.align,M=b.items||(b.items={}),H=b.link,O=b.isHeader?n:w,aa=M.background,d=Oa(y+m)-.5,C={x:Oa(L+E)-.5,y:d,width:x+.5,height:v.h+D+.5,radius:0,fill:b.bgColor||Na,"stroke-dasharray":u,stroke:l,cursor:H?"pointer":"","stroke-width":0},aa?aa.attr(C):(M.background=p.rect(O).attr(C).hover(F,ca),N={isHeader:b.isHeader,label:b.text,vAlign:b.vAlign,align:b.align,link:b.link,id:b.id},M.background.click(q).data("dataObj",b).data("eventArgs",
N).data("data",{y:d,gridObj:b,rollOverColor:k,useHover:!0,useNext:!0,height:v.h+D+.5,hoverEle:ra.items.hoverEle})),b.isNaN||(v=b.dimension,C=b.text,C=b.align,aa=M.label,C=b.text,Ua(C)&&""!==C&&(ba=b.style,t.setStyle(ba),I=t.getSmartText(C,x-8,X(Ta(ba.lineHeight,10),v.h)),ba.title=I.oriText,C=b.align,C={text:I.text,x:L+x*ib[C]+Wa[C],y:y+v.h-v.h*vb[b.vAlign],"text-anchor":Va[C],cursor:H?"pointer":"","vertical-align":b.vAlign},aa?aa.attr(C):M.label=p.text(O).attr(C).css(ba).hover(F,ca).click(q).data("eventArgs",
N).data("dataObj",b).data("data",{y:d,gridObj:b,rollOverColor:k,useHover:!0,height:v.h+D+.5,useNext:!0,hoverEle:ra.items.hoverEle}))),b.xPos=L,b.yPos=Oa(y+v.h)-r%2*.5,h.push("M",L,b.yPos,"h",x),(aa=M.hBorder)?aa.attr("path",h):M.hBorder=p.path(h,O).attr({"stroke-dasharray":u,stroke:l,"stroke-width":r}),y+=v.h,b.nextCol||(E=D,m-=0,aa=b.first.items.vBorder,C=["M",Oa(L+x)-r%2*.5,z,"v",Y],aa?aa.attr("path",C):b.first.items.vBorder=p.path(C,n).attr({"stroke-dasharray":u,stroke:l,"stroke-width":r}),b.nextRow&&
!b.isLast&&(b.first.items.dragEle||(b.first.items.dragEle=p.path(C,g.gridTracker).attr({stroke:c.gridResizeBarColor,"stroke-width":c.gridResizeBarThickness,visibility:"hidden"})),b.first.items.tracker||(b.first.items.tracker=p.path(C,g.gridTracker).attr({stroke:Na,ishot:!0,"stroke-width":30}).css("cursor",ma.svg&&"ew-resize"||"e-resize").drag(this.dragMove,this.dragStart,this.dragUp).data("drag-options",{grid:b.first,xPos:Oa(L+x)-r%2*.5,chart:a})))),b=b.nextCol},dragStart:function(){var b=this.data("drag-options"),
a=b.grid,J=a.items,c=a.nextRow,e={style:{lineHeight:16}},k=a.nextCol.style||e,t=c&&c.nextCol&&c.nextCol.style||e,z=b.chart,f=z.canvasLeft,g=a.dimension,k=X(Ta(a.style.lineHeight,10),Ta(k.lineHeight,10))+2,e=X(Ta((c||e).style.lineHeight,10),Ta(t.lineHeight,10))+2;b.leftSideLimit=f+d(a.dimension.x,0)+k;b.rightSideLimit=f+d(c&&c.dimension.x+c.dimension.w,g.x+g.w)-e;b.origX=b.lastX||(b.lastX=0);J.dragEle.show();z.trackerClicked=!0;b.draged=!1},dragMove:function(b){var a=this.data("drag-options"),d=a.grid.items,
c=a.xPos+b,e=a.leftSideLimit,k=a.rightSideLimit;c<e&&(b=e-a.xPos);c>k&&(b=k-a.xPos);c={transform:"t"+(a.origX+b)+kc+0};this.attr(c);d.dragEle.attr(c);a.draged=!0;a.lastX=b},dragUp:function(){var b=this.data("drag-options"),a=b.chart,d=b.grid,c=d.nextRow,e=a.canvasLeft,k=d.dimension,t=c&&c.dimension,z=d.items,f={hcJSON:{dataTable:{}}};a.trackerClicked=!1;z.dragEle.hide();b.draged&&(k.w=b.xPos+b.lastX-e-k.x,d.nextCol&&(d.nextCol.dimension.w=k.w),f.hcJSON.dataTable[d.key]={dimension:k},c&&(t.w+=t.x-
k.x-k.w,t.x=k.x+k.w,c.dimension.w=t.w,c.dimension.x=t.x,a.drawProcess(c),f.hcJSON.dataTable[c.key]={dimension:t}),a.drawProcess(d),gb(a.logic.chartInstance.jsVars._reflowData,f,!0),b.xPos+=b.lastX,b.lastX+=b.origX)},drawCategories:function(){var b=this,a=b.options,e=a.chart,c=b.paper,p=b.layers,k=b.logic.smartLabel,t=b.canvasTop,z=a.categories,f=a.dataTable.processHeader,g=z.FCCAT_0_0,w=z.axis,n=z.endX,r=z.startX,D=n-r,l=e.ganttLineThickness,u=f.totalPH+f.dimension.h,E=[],m=[],h=p.dataset,p=p.ganttHeaderLayer,
y,x,R,F,H,Y,M,N,O,C,aa,I,ba,L,v;ba=function(a){V.call(this,b,a,"CategoryClick")};L=function(a){ja=clearTimeout(ja);if(!ea||ea.removed)ea=null;ea&&b.gridOutHandler.call(ea);b.gridHoverHandler.call(this);V.call(this,b,a,"CategoryRollOver")};v=function(a){ea=this;ja=clearTimeout(ja);ja=setTimeout(function(){b.gridOutHandler.call(ea)},500);V.call(ea,b,a,"CategoryRollOut")};F=z.items||(z.items={});f=a.dataTable.processHeader;for(F.hoverEle=c.rect(0,t+f.dimension.h,50,f.totalPH,0,h).attr({fill:Na,visibility:"hidden",
"stroke-width":0});g;)x=D/g.dimension.numCat,H=r+x*(g.index+1),O=H-x,N=g.dimension.h,C=O,I=t+g.dimension.y,Y=g.align,M=g.vAlign,R=g.link,F=g.items||(g.items={}),x=!(!g.nextRow&&g.nextCol),aa=a.verticalScroll.enabled&&x?a.scrollOptions.height:0,y={align:g.align,vAlign:g.vAlign,link:g.link,text:g.text},O=C=d(w.getPixel(g.start),O),H=d(w.getPixel(!x&&g.nextCol.start||(x?X(g.end||0,a.max):void 0)),H),x=H-O,C=xa(C)+.5,I=xa(I)+.5,g.isLast&&(E.push("M",C,I,"v",u-g.dimension.y),I-=.5*l,N-=l,e.extendCategoryBg&&
c.rect(C,I,x,u,0,h).attr({fill:g.bgColor,"stroke-width":0,stroke:e.ganttLineColor}).toBack()),F.background=c.rect(C,I,x+aa,N,0,p).attr({fill:g.bgColor,"stroke-width":0,cursor:R?"pointer":"",stroke:e.ganttLineColor}).click(ba).data("eventArgs",y).data("dataObj",g).hover(L,v).data("data",{x:C,width:x,gridObj:g,hoverEle:z.items.hoverEle}),m.push("M",C,I,"v",N),g.nextRow&&m.push("M",r,I+N,"H",n+aa),k.setStyle(g.style),H=k.getSmartText(g.text,x-5,N),g.style.title=H.oriText,F.label=c.text(p).attr({text:H.text,
x:C+x*ib[Y]+Wa[Y],y:I+N-N*vb[M],"text-anchor":Va[Y],cursor:R?"pointer":"","vertical-align":M}).css(g.style).hover(L,v).click(ba).data("eventArgs",y).data("dataObj",g).data("data",{x:C,width:x,gridObj:g,hoverEle:z.items.hoverEle}),g=g.nextCol;for(;f;)E.push("M",z.startX,f.yPos,"H",n),f=f.nextCol;F=z.items||(z.items={});F.headerGrid=c.path(m,p).attr({"stroke-dasharray":e.ganttLineDashStyle,"stroke-width":l,stroke:e.ganttLineColor});F.processGrid=c.path(E,h).attr({"stroke-dasharray":e.ganttLineDashStyle,
"stroke-width":e.ganttLineThickness,stroke:e.ganttLineColor})},drawScroller:function(){var b=this,a=b.options,e=b.paper,c=b.layers,p=b.canvasTop,k=b.canvasHeight,t=a.scrollOptions,z=a.categories,f=z.startX,g=z.endX-f,w=t.flatScrollBars,n={hcJSON:{categories:{scroll:{}}}},r=c.dataset,D=c.datalabels,l=c.ganttTracker,u=c.ganttHeaderLayer,E=b.logic.chartInstance&&b.logic.chartInstance.jsVars._reflowData||{},m=a.chart,h=c.gridLayer,y=(f=a.dataTable)&&f.processHeader,x=b.canvasLeft,R=b.canvasWidth,F=m.gridBorderThickness,
H=m.totalGridWidth,Y=Fa(m.ganttStartX,H)+F,M=z.scroll,N=f&&f.__scrollOptions,O=a.verticalScroll,C={hcJSON:{dataTable:{__scrollOptions:{}},verticalScroll:{}}},aa=C.hcJSON.dataTable.__scrollOptions,I=y.totalPH,ba=c.gridHeaderLayer,L=c.gridTracker,v,q,f=d(z.startX,m.ganttStartX),c=c.scroll=c.scroll||e.group("scroll").insertAfter(l);M.enabled&&(a=z.visibleW/g,M.scroller=e.scroller(f,p+k-t.height,z.visibleW,t.height,!0,{showButtons:t.showButtons,displayStyleFlat:w,buttonWidth:t.buttonWidth,scrollRatio:a,
scrollPosition:M.startPercent},c).attr({"scroll-display-style":w,fill:t.color}).scroll(function(a){q=-xa(a*(g-z.visibleW));r&&r.transform(["T",q,r.data("vOffset")]);D&&D.transform(["T",q,D.data("vOffset")]);l&&l.transform(["T",q,l.data("vOffset")]);u&&u.transform(["T",q,0]);r&&r.data("hOffset",q);D&&D.data("hOffset",q);l&&l.data("hOffset",q);n.hcJSON.categories.scroll.startPercent=a;gb(E,n,!0)}),function(){var a;ma.eve.on("raphael.scroll.start."+M.scroller.id,function(c){a=c;ga.raiseEvent("scrollstart",
{scrollPosition:c},b.logic.chartInstance)});ma.eve.on("raphael.scroll.end."+M.scroller.id,function(c){ga.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},b.logic.chartInstance)})}(),M.startPercent&&(q=-xa(M.startPercent*(g-z.visibleW)),r&&r.data("hOffset",q),D&&D.data("hOffset",q),l&&l.data("hOffset",q),u&&u.transform(["T",q,0]),r&&r.transform(["T",q,r.data("vOffset")]),D&&D.transform(["T",q,r.data("vOffset")]),l&&l.transform(["T",q,r.data("vOffset")])));N.enabled&&(N.scroller=e.scroller(x,
p+k-t.height,Y,t.height,!0,{showButtons:t.showButtons,displayStyleFlat:w,buttonWidth:t.buttonWidth,scrollRatio:Y/H,scrollPosition:N.startPercent},c).attr({"scroll-display-style":w,fill:t.color}).scroll(function(a){q=-xa(a*(H-Y));h&&h.transform(["T",q,h.data("vOffset")]);ba&&ba.transform(["T",q,0]);L&&L.transform(["T",q,L.data("vOffset")]);h.data("hOffset",q);ba.data("hOffset",q);L.data("hOffset",q);aa.startPercent=a;gb(E,C,!0)}),function(){var a;ma.eve.on("raphael.scroll.start."+N.scroller.id,function(c){a=
c;ga.raiseEvent("scrollstart",{scrollPosition:c},b.logic.chartInstance)});ma.eve.on("raphael.scroll.end."+N.scroller.id,function(c){ga.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},b.logic.chartInstance)})}(),N.startPercent&&(q=-xa(N.startPercent*(H-Y)),h&&h.transform(["T",q,0]),L&&L.transform(["T",q,0]),ba&&ba.transform(["T",q,0]),h.data("hOffset",q),L.data("hOffset",q)));O.enabled&&(v=m.processHeight-y.dimension.h,O.scroller=e.scroller(x+R-t.height,p+y.dimension.h,t.height,m.processHeight-
y.dimension.h,!1,{showButtons:t.showButtons,displayStyleFlat:w,buttonWidth:t.buttonWidth,scrollRatio:v/I,scrollPosition:O.startPercent},c).attr({"scroll-display-style":w,fill:t.color}).scroll(function(a){q=-xa(a*(I-v));h&&h.transform(["T",h.data("hOffset"),q]);r&&r.transform(["T",r.data("hOffset"),q]);D&&D.transform(["T",D.data("hOffset"),q]);l&&l.transform(["T",l.data("hOffset"),q]);L&&L.transform(["T",L.data("hOffset"),q]);h.data("vOffset",q);L.data("vOffset",q);r.data("vOffset",q);l.data("vOffset",
q);D.data("vOffset",q);C.hcJSON.verticalScroll.startPercent=a;gb(E,C,!0)}),function(){var a;ma.eve.on("raphael.scroll.start."+O.scroller.id,function(c){a=c;ga.raiseEvent("scrollstart",{scrollPosition:c},b.logic.chartInstance)});ma.eve.on("raphael.scroll.end."+O.scroller.id,function(c){ga.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},b.logic.chartInstance)})}(),O.startPercent&&(q=-xa(O.startPercent*(I-v)),h&&h.transform(["T",h.data("hOffset"),q]),r&&r.transform(["T",r.data("hOffset"),
q]),D&&D.transform(["T",D.data("hOffset"),q]),l&&l.transform(["T",l.data("hOffset"),q]),L&&L.transform(["T",L.data("hOffset"),q]),h.data("vOffset",q),L.data("vOffset",q),r.data("vOffset",q),D.data("vOffset",q),l.data("vOffset",q)))},finalizeScrollPlots:function(){var b=this,a=b.options,d=b.canvasTop,c=a.categories,e=c.endX,k=c.startX,t=c.scroll,z=a.chart,f=a.dataTable,g=f&&f.processHeader,w=b.canvasLeft,n=z.gridBorderThickness,r=z.totalGridWidth,D=Fa(z.ganttStartX,r)+n,l,u,E,m,h,y=e-k-c.visibleW,
e=b.container,x=f&&f.__scrollOptions,R=a.verticalScroll,V=g.totalPH,H=z.processHeight-g.dimension.h,Y,M,N,O,C,t=c.scroll,a=function(a){var e=b.elements.canvas,f=O.left,n=O.top,p=a.type,q=ub&&F.getTouchEvent(a)||mc,f=a.layerX||q.layerX||(a.pageX||q.pageX)-f;a=a.layerY||q.layerY||(a.pageY||q.pageY)-n;switch(p){case "dragstart":C=e.isPointInside(f,a);Y=f>k&&f<k+c.visibleW;N=f>w&&f<k+c.visibleW&&a>d+g.dimension.h;M=f<k;l=C&&f||null;u=C&&a||null;break;case "dragend":C=!1;h=m=E=u=l=void 0;break;default:if(!C||
b.trackerClicked)break;e=f-l;p=a-u;l=f;u=a;Y&&t&&t.scroller&&(E=t.scroller.attrs["scroll-position"]-e/y,t.scroller.attr({"scroll-position":E}));N&&R&&R.scroller&&(m=R.scroller.attrs["scroll-position"]-p/(V-H),R.scroller.attr({"scroll-position":m}));M&&x&&x.scroller&&(h=x.scroller.attrs["scroll-position"]-e/(r-D),x.scroller.attr({"scroll-position":h}))}};ub&&(O=F.getPosition(e),e&&(oc(e,"dragstart drag dragend",a),nc(e,"dragstart drag dragend",a)))},gridHoverHandler:function(){var b=this.data("data"),
a=b.gridObj,d=!!a.prevRow,c={};if(!a.isHeader)if(b.x&&(c.x=b.x),b.y&&(c.y=b.y),b.width&&(c.width=b.width),b.height&&(c.height=b.height),a.hoverColor&&(c.fill=a.hoverColor),a.usePlotHover&&b.hoverEle.attr(c).show(),b.useNext&&a.useHover){for(;a&&d;)a=a.prevRow,d=!!a.prevRow;for(;a;)a.items.background.attr("fill",a.hoverColor),a=a.nextRow}else a.useHover&&a.items.background.attr("fill",a.hoverColor)},gridOutHandler:function(){var b=this.data("data"),a=b.gridObj,d=!!a.prevRow;if(!a.isHeader)if(a.usePlotHover&&
b.hoverEle.hide(),b.useNext&&a.useHover){for(;a&&d;)a=a.prevRow,d=!!a.prevRow;for(;a;)a.items.background.attr("fill",a.bgColor||Na),a=a.nextRow}else a.useHover&&a.items.background.attr("fill",a.bgColor)},drawAxes:function(){if(this.options.dataTable){Ra["renderer.cartesian"].drawAxes.call(this,arguments);var b=this.options,a=b.chart,e=this.paper,c=this.layers,p=c.layerBelowDataset,k=c.layerAboveDataset,t=c.gridLayer,z=c.dataset,f=b.dataTable,g=b.categories,f=f&&f.processHeader,w=this.canvasTop,z=
this.canvasLeft,t=a.gridBorderThickness,n=Fa(a.ganttStartX,a.totalGridWidth)+t,r=f.dimension,D=r.h,r=a.processHeight-r.h,l=d(g.startX,a.ganttStartX),g=g.visibleW,a=.5*a.ganttLineThickness,t=.5*t,t=c.gridLayer=c.gridLayer||e.group("grid",p).attr({"clip-rect":[z,w+D+t,n,r-t]});c.gridHeaderLayer=c.gridHeaderLayer||e.group("grid-header",p).attr({"clip-rect":[z,w,n,D+r]});p=c.gridTracker=c.gridTracker||e.group("grid-tracker",p).attr({"clip-rect":[z,w,n,D+r]});t.data("vOffset",0);t.data("hOffset",0);p.data("vOffset",
0);p.data("hOffset",0);c.ganttHeaderLayer=c.ganttHeaderLayer||e.group("gantt",k).attr({"clip-rect":[l,w,g+(b.verticalScroll.enabled?b.scrollOptions.height:0),this.chartHeight]});z=c.dataset.attr({"clip-rect":[l,w+D-a,g,r+a]});b=c.datalabels.attr({"clip-rect":[l,w+D-a-10,g,r+a+10]});e=c.ganttTracker=e.group("gantt-hot",c.tracker).attr({"clip-rect":[l,w+D-a,g,r+a]});z.data("vOffset",0);z.data("hOffset",0);b.data("vOffset",0);b.data("hOffset",0);e.data("vOffset",0);for(e.data("hOffset",0);f;)this.drawProcess(f),
f=f.nextRow;this.drawCategories()}},drawPlotGantt:function(b){var a=this,J=a.options,c=J.chart,p=a.paper,k=a.layers,t=b.data,z=b.items,f=t.length,g=k.dataset,w=k.datalabels,n=J.dataTable,r=n.processHeader,D=J.categories,l=D.axis,u=a.canvasTop,E=c.taskBarRoundRadius,f=J.plotOptions.series,m=isNaN(+f.animation)&&f.animation.duration||1E3*f.animation,h=J.tasksMap||(J.tasksMap={}),y=J.milestone,x=J.trendlines,F=r.dimension.h,ea=c.taskDatePadding,H,Y,M,N,O,C,aa,I,ba,L,v,q,U,ca,ga,X,ja,B,S,da,G;b.graphics=
[];ga=g.shadows||(g.shadows=p.group("shadows",g));f=x&&x.length;for(b=0;b<f;b+=1)v=x[b],v.end||(v.end=v.start),v.end&&(S=l.getPixel(v.start),X=l.getPixel(v.end),da=v.thickness,J=v.items||(v.items={}),H=void 0,v.isTrendZone?(L=["M",S+.5*(X-S),u+F,"v",u+r.totalPH],da=X-S):(L=["M",S,u+F,"L",X,u+F+r.totalPH],H=v.dashedStyle),J.trendLine=p.path(L,g).attr({stroke:v.color,"stroke-width":da,"stroke-dasharray":H}),Ua(v.displayValue)&&""!==v.displayValue&&(J.label=p.text(k.ganttHeaderLayer).attr({text:v.displayValue,
x:L[1],y:0}).css(v.style),H=J.label._getBBox().height,v=u+c.processHeight+(!D.scroll.enabled||c.marginBottom<H?.5*H:-(.5*H)-5),J.label.attr("y",v)));w.hide();k=function(){w.show()};x=r=function(b){V.call(this,a,b)};D=function(b){V.call(this,a,b,"DataPlotRollOver")};u=function(b){V.call(this,a,b,"DataPlotRollOut")};F=function(b){b&&b.click(function(b){V.call(this,a,b)}).hover(function(b){var c=this.data("dataObj");V.call(this,a,b,"DataPlotRollOver");c.showHoverEffect&&a.taskHoverHandler.call(this,
a)},function(b){var c=this.data("dataObj");V.call(this,a,b,"DataPlotRollOut");c.showHoverEffect&&a.taskHoverOutHandler.call(this,a)}).data("dataObj",B).data("eventArgs",Y)};f=t.length;for(b=0;b<f;b+=1)B=t[b],J=B.processId,v=n[J],X=ja=B.color,J=B.items||(B.items={}),L=B.animation?m||1E3:0,v&&(G=B.borderThickness,S=xa(l.getPixel(B.start)),da=cc(N=l.getPixel(B.end)-S),S&&da&&(M=v.dimension.h,v=v.yPos-M,H=M*(/%/g.test(B.height)&&.01*Ib(B.height,10))||d(B.height,M),q=M*(/%/g.test(B.topPadding)&&.01*Ib(B.topPadding,
10))||d(B.topPadding,M),v+=Fa(q,M-H),ca=.5*H,U=B.toolText,q=B.link,(M=z[b])||(M=z[b]={index:b,dataLabel:null,start:B.start,end:B.end,startLabel:null,endLabel:null,tracker:null}),B.index=b,O=e(B.id,b),""!==O&&h[O]&&(h[O].items=M,h[O].x=S,h[O].y=v,h[O].h=H,h[O].w=da),N=O=C=aa=I=ba=null,B.showAsGroup?(L?(N=p.path(["M",S,v],g),N.animate({path:["M",S,v,"v",H,"L",S+ca,v+ca,"H",S+da-ca,"L",S+da,v+H,"v",-H,"H",S]},L,"normal",k)):(N=p.path(["M",S,v,"v",H,"L",S+ca,v+ca,"H",S+da-ca,"L",S+da,v+H,"v",-H,"H",S],
g),k&&k()),N.attr({fill:X,stroke:B.borderColor,cursor:q?"pointer":"",ishot:!0,"stroke-width":B.borderThickness}).tooltip(U).shadow(c.shadow&&B.shadow,ga)):(-1!==B.percentComplete&&(N=da*B.percentComplete*.01,X=Na,O=J.taskFill=p.rect(S,v,0,H,0,g).attr({fill:ja,cursor:q?"pointer":"",ishot:!0,"stroke-width":0,width:L?0:N||1}).tooltip(U),L&&O.animate({width:N||1},L,"normal"),C=p.rect(S,v,0,H,0,g).attr({fill:B.slackColor,cursor:q?"pointer":"",ishot:!0,"stroke-width":0,x:L?S:S+N||1,width:L?0:da-N||1}).tooltip(U),
L&&C.animate({x:S+N||1,width:da-N||1},L,"normal")),J=ma.crispBound(S,v,da,H,G),N=p.rect(J.x,J.y,0,J.height,E,g).attr({fill:X,stroke:B.borderColor,cursor:q?"pointer":"",ishot:!0,"stroke-width":B.borderThickness,width:L?0:J.width||1}).tooltip(U).shadow(c.shadow&&B.shadow,ga),L?N.animate({width:J.width||1},L,"normal",k):k&&k()),Ua(B.label)&&""!==B.label&&(J=B.labelAlign,aa=p.text().attr({text:B.label,x:S+da*ib[J]+Wa[J],"text-anchor":Va[J],cursor:q?"pointer":"",ishot:!0,y:v-.5*Ta(B.style.lineHeight,10)-
c.taskLabelPadding}).css(B.style),w.appendChild(aa)),Ua(B.startDate)&&""!==B.startDate&&(I=p.text().attr({text:B.startDate,x:S-2-ea,y:v+.5*H,cursor:q?"pointer":"",ishot:!0,"text-anchor":"end"}).css(B.style),w.appendChild(I)),Ua(B.endDate)&&""!==B.endDate&&(ba=p.text().attr({text:B.endDate,x:S+da+2+ea,y:v+.5*H,cursor:q?"pointer":"",ishot:!0,"text-anchor":"start"}).css(B.style),w.appendChild(ba)),M.graphic=N,M.percentCompleteGraphic=O,M.slackGraphic=C,M.dataLabel=aa,M.startLabel=I,M.endLabel=ba,Y={processId:B.processId,
taskId:B.id,start:B._start,end:B._end,showAsGroup:B.showAsGroup,link:B.link,sourceType:"task",percentComplete:-1!==B.percentComplete&&B.percentComplete},O&&O.click(r).hover(D,u).data("eventArgs",Y),C&&C.click(x).data("eventArgs",Y),Sa([N,aa,I,ba],F)));z=function(b){V.call(this,a,b,"MilestoneClick")};n=function(b){var c=this.data("dataObj");V.call(this,a,b,"MilestoneRollOver");c.showHoverEffect&&c.items.graphic.attr({fill:c.hoverFillColor,stroke:c.hoverBorderColor,"fill-opacity":c.hoverFillAlpha,"stroke-opacity":c.hoverBorderAlpha})};
E=function(b){var c=this.data("dataObj");V.call(this,a,b,"MilestoneRollOut");c.showHoverEffect&&c.items.graphic.attr({fill:c.fillColor,stroke:c.borderColor,"fill-opacity":c.fillAlpha,"stroke-opacity":c.borderAlpha})};this.drawConnectors();J=null;f=y&&y.length;for(b=0;b<f;b+=1)c=y[b],v=h[c.taskId],J=c.items||(c.items={}),v&&(t=ma.animation({"fill-opacity":c.fillAlpha,"stroke-opacity":c.borderAlpha},m,"normal"),Y={sides:c.sides,date:c.origDate,radius:c.radius,taskId:c.taskId,toolText:c.toolText,link:c.link,
numSides:c.numSides},J.graphic=p.polypath(c.numSides,l.getPixel(c.date.ms),v.y+.5*v.h,d(c.radius,.6*v.h),c.startAngle,c.depth,g).attr({fill:c.fillColor,"fill-opacity":m?0:c.fillAlpha,stroke:c.borderColor,"stroke-opacity":m?0:c.borderAlpha,groupId:"gId"+b,ishot:!0,cursor:c.link?"pointer":"","stroke-width":c.borderThickness}).tooltip(c.toolText).click(z).data("eventArgs",Y).data("dataObj",c),J.label=p.text().attr({text:c.displayValue,x:l.getPixel(c.date.ms),y:v.y+.5*v.h,groupId:"gId"+b,cursor:c.link?
"pointer":"",ishot:!0,"text-anchor":"middle"}).css(c.style).tooltip(c.toolText).click(z).data("eventArgs",Y).data("dataObj",c),w.appendChild(J.label),m&&J.graphic.animate(t.delay(m)),J.graphic.hover(n,E),J.label.hover(n,E))},taskHoverOutHandler:function(b){var a=b.options.tasksMap;b=this.data("dataObj");var a=a[e(b.id,b.index)].items,d={fill:b.color,stroke:b.borderColor,"stroke-width":b.borderThickness,"stroke-dasharray":b.dashedStyle};-1===b.percentComplete||b.showAsGroup||(a.slackGraphic.attr({fill:b.slackColor}),
a.percentCompleteGraphic.attr({fill:b.color}),delete d.fill);a.graphic.attr(d)},taskHoverHandler:function(b){var a=b.options.tasksMap;b=this.data("dataObj");var a=a[e(b.id,b.index)].items,d={fill:b.hoverFillColor,stroke:b.hoverBorderColor};-1===b.percentComplete||b.showAsGroup||(a.slackGraphic.attr({fill:b.slackHoverColor}),a.percentCompleteGraphic.attr({fill:b.hoverFillColor}),delete d.fill);a.graphic.attr(d)},drawConnectors:function(){var b=this,a=b.paper,d=b.options,c=d.chart.connectorExtension,
e=d.connectors,k=d.tasksMap,t=e.length,z=b.layers.dataset,f=[],d=d.plotOptions.series,d=isNaN(+d.animation)&&d.animation.duration||1E3*d.animation,g,w,n,r,D,l,u,E,m,h,y,x,F,U,H;F=function(a){V.call(this,b,a,"ConnectorClick")};U=function(a){var c=this.data("dataObj"),d=k[c.fromTaskId],e=k[c.toTaskId],f={stroke:c.hoverColor,"stroke-dasharray":c.dashedStyle,"stroke-width":c.hoverThickness};V.call(this,b,a,"ConnectorRollOver");c.showHoverEffect&&(Sa([d,e],function(a){var b={fill:a.dataObj.hoverFillColor,
stroke:a.dataObj.hoverBorderColor};-1===a.dataObj.percentComplete||a.dataObj.showAsGroup||(a.items.slackGraphic.attr({fill:a.dataObj.slackHoverColor}),a.items.percentCompleteGraphic.attr({fill:a.dataObj.hoverFillColor,stroke:a.dataObj.hoverBorderColor}),delete b.fill);a.items.graphic.attr(b)}),c.items.connector.attr(f))};H=function(a){var c=this.data("dataObj"),d=k[c.fromTaskId],e=k[c.toTaskId],f={stroke:c.color,"stroke-width":c.thickness,"stroke-dasharray":c.dashedStyle};V.call(this,b,a,"ConnectorRollOut");
c.showHoverEffect&&(Sa([d,e],function(a){var b={fill:a.dataObj.color,stroke:a.dataObj.borderColor,"stroke-width":a.dataObj.borderThickness,"stroke-dasharray":a.dataObj.dashedStyle};-1===a.dataObj.percentComplete||a.dataObj.showAsGroup||(a.items.slackGraphic.attr({fill:a.dataObj.slackColor}),a.items.percentCompleteGraphic.attr({fill:a.dataObj.color}),delete b.fill);a.items.graphic.attr(b)}),c.items.connector.attr(f))};for(g=0;g<=t;g+=1)if(n=e[g]||{},l=n.fromTaskId,r=n.toTaskId,w=k[l],m=k[r],r=n.items||
(n.items={}),w&&m){h=w.y+.5*w.h;y=m.y+.5*m.h;D=h==y;l=w.x;u=w.x+w.w;E=m.x;m=m.x+m.w;x=x=0;0===n.fromTaskConnectStart&&1===n.toTaskConnectStart&&(x=1);0===n.fromTaskConnectStart&&0===n.toTaskConnectStart&&(x=2);1===n.fromTaskConnectStart&&1===n.toTaskConnectStart&&(x=3);1===n.fromTaskConnectStart&&0===n.toTaskConnectStart&&(x=4);if(D)switch(w=w.height,x){case 1:x=(E-u)/10;f=["M",u,h,u+x,h,"L",u+x,h,u+x,h-w,"L",u+x,h-w,E-x,h-w,"L",E-x,h-w,E-x,h,"L",E-x,h,E,y,"L",m+c,y,m,y];break;case 2:f=["M",u,h,u+
c,h,"L",u+c,h,u+c,h-w,"L",u+c,h-w,m+c,h-w,"L",m+c,y-w,m+c,y];break;case 3:f=["M",l,h,l-c,h,"L",l-c,h,l-c,h-w,"L",l-c,h-w,E-c,h-w,"L",E-c,h-w,E-c,h,"L",E-c,h,E,h];break;case 4:f=["M",l,h,l-c,h,"L",l-c,h,l-c,h-w,"L",l-c,h-w,m+c,h-w,"L",m+c,h-w,m+c,h,"L",m+c,h,m,h]}else switch(x){case 1:f=["M",u,h,u+(E-u)/2,h,"L",u+(E-u)/2,h,u+(E-u)/2,y,"L",u+(E-u)/2,y,E,y];f=u<=E?["M",u,h,u+(E-u)/2,h,"L",u+(E-u)/2,h,u+(E-u)/2,y,"L",u+(E-u)/2,y,E,y]:["M",u,h,u+c,h,"L",u+c,h,u+c,h+(y-h)/2,"L",u+c,h+(y-h)/2,E-c,h+(y-h)/
2,"L",E-c,h+(y-h)/2,E-c,y,"L",E-c,y,E,y];break;case 2:x=0>m-u?0:m-u;f=["M",u,h,u+c+x,h,"L",u+c+x,h,u+c+x,y,"L",u+c+x,y,m,y];break;case 3:x=0>l-E?0:l-E;f=["M",l,h,l-c-x,h,"L",l-c-x,h,l-c-x,y,"L",l-c-x,y,E,y];break;case 4:f=l>m?["M",l,h,l-(l-m)/2,h,"L",l-(l-m)/2,h,l-(l-m)/2,y,"L",l-(l-m)/2,y,m,y]:["M",l,h,l-c,h,"L",l-c,h,l-c,h+(y-h)/2,"L",l-c,h+(y-h)/2,m+c,h+(y-h)/2,"L",m+c,h+(y-h)/2,m+c,y,"L",m+c,y,m,y]}r.connector?r.connector.animate({path:f}):(l=ma.animation({"stroke-opacity":n.alpha},d,"normal"),
r.connector=a.path(f,z).attr({stroke:n.color,"stroke-opacity":0,"stroke-width":n.thickness,"stroke-dasharray":n.dashedStyle}).animate(l.delay(d)));l={fromTaskId:n.fromTaskId,toTaskId:n.toTaskId,fromTaskConnectStart:n.fromTaskConnectStart,toTaskConnectStart:n.toTaskConnectStart,link:n.link,sourceType:"connector"};r.tracker=a.path(f,z).attr({stroke:Na,"stroke-width":X(n.thickness,10),ishot:!0,cursor:n.link?"pointer":""}).data("dataObj",n).data("eventArgs",l).click(F);r.tracker.hover(U,H)}}},Ra["renderer.cartesian"])}]);
